"""Build-context generator for arbitrary repos.

Arbitrary-repo triage needs a valid Docker build context for the local
sandbox. Many repos (e.g. dvpwa) ship only `Dockerfile.app`/`Dockerfile.db`
or none at all. This script derives a minimal `Dockerfile` (+ `.dockerignore`)
from the repo layout so `sandbox_build` can operate on any repo.

Behavior:
  - Default output directory is the repo itself (Docker context = repo).
  - ``--out DIR`` builds a COMPLETE context: the repo tree is copied into DIR
    (excluding VCS/venv/build dirs) and the Dockerfile is generated there, so
    COPY sources never escape the context.
  - Existing `Dockerfile`/`.dockerignore` are never silently overwritten;
    pass ``--force`` to replace them explicitly.
  - Raises ValueError when no runnable entry can be derived — a Dockerfile
    referencing a nonexistent entry would start-fail in the sandbox.

Never runs exploit code; this only generates build context.
"""

import argparse
import itertools
import json
import os
import re
import shlex
import stat
import shutil
import sys

if __package__ in (None, ""):  # direct-file execution: make the package importable
    sys.path.insert(0, os.path.dirname(os.path.dirname(
        os.path.dirname(os.path.abspath(__file__)))))
    from agent.analyzer import deps
else:
    from . import deps

_ENTRY_CANDIDATES = ("main.py", "app.py", "run.py", "server.py", "wsgi.py",
                     "manage.py", "index.js", "server.js", "app.js", "main.js")
_SKIP = deps._SKIP_PARTS + ("tests", "test", ".github", "dist", "build",
                            "static", "assets", "vendor", "public")


def _find_entry(repo_path):
    for root, dirs, files in os.walk(repo_path):
        dirs[:] = [d for d in dirs if d not in _SKIP]
        for fname in files:
            if fname in _ENTRY_CANDIDATES:
                return os.path.relpath(os.path.join(root, fname), repo_path)
    return None


# Only python/node official-family images are reused — repo content is
# untrusted (ADR-016) and must not pick executable image content such as a
# database or arbitrary registry image for the sandbox runtime.
_BASE_ALLOWLIST_RE = re.compile(
    r"^(python|node)(:[A-Za-z0-9][A-Za-z0-9._-]*)?(@sha256:[a-f0-9]{64})?$")
_FROM_RE = re.compile(r"^\s*FROM\s+(\S+)", re.I)
# Marker written into every generated Dockerfile so the detector skips our
# own artifacts on re-runs (a generated file must never become the source
# of the repo's declared base).
_GENERATED_MARKER = "# Generated by PatchProof gen_context (safe to delete)."


def _detect_base_image(repo_path, entry_lang):
    """Reuse the base the repo itself declares for its runtime, or None.

    Scans prioritized Dockerfile* files (canonical `Dockerfile`, then
    runtime-suffixed variants like `.app`/`.web` — never db/builder files)
    and returns the FIRST ACCEPTABLE FROM: an allowlisted official
    python/node image (well-formed tag or 64-hex digest) matching the entry
    language. Anything else — parametrized `FROM ${VAR}`, foreign images,
    malformed refs, wrong language — is skipped and the scan CONTINUES to
    later files; None only when no file yields an acceptable FROM (the
    caller then uses the generic default). Our own generated artifacts are
    marker-skipped. Legacy apps (e.g. dvpwa) pin python:alpine3.8-era bases
    their requirements actually build on; a generic default would fail
    those.
    """
    preferred = ["Dockerfile", "Dockerfile.app", "Dockerfile.web",
                 "Dockerfile.prod", "Dockerfile.api", "Dockerfile.server"]
    prefix = "python" if entry_lang == "py" else "node"
    files = []
    for root, dirs, names in os.walk(repo_path):
        dirs[:] = [d for d in dirs if d not in _SKIP]
        for fname in names:
            if fname == "Dockerfile" or fname.startswith("Dockerfile."):
                rel = os.path.relpath(os.path.join(root, fname), repo_path)
                files.append(rel)
    files.sort(key=lambda f: (preferred.index(os.path.basename(f))
                              if os.path.basename(f) in preferred else 99, f))
    for rel in files:
        path = os.path.join(repo_path, rel)
        try:
            # Only regular files: repo-controlled symlinks (FIFO/device
            # targets or escapes outside the repo) are never followed.
            if not stat.S_ISREG(os.lstat(path).st_mode):
                continue
            with open(path, encoding="utf-8", errors="replace") as fh:
                head = fh.readline()
                if head.startswith("# Generated by PatchProof"):
                    continue  # our own earlier artifact
                for line in itertools.chain((head,), fh):
                    # Streamed, never materialized: repo-controlled files
                    # can be arbitrarily large.
                    parts = line.split()
                    if not parts or parts[0].upper() != "FROM":
                        continue
                    img = next((p for p in parts[1:]
                                if not p.startswith("--")), None)
                    if not img or "${" in img:
                        continue  # no image / unresolvable parametrization
                    if not _BASE_ALLOWLIST_RE.match(img):
                        continue  # untrusted image — skip file
                    if img.split(":")[0].split("@")[0] != prefix:
                        continue  # wrong language for this entry
                    return img, rel
        except OSError:
            continue
    return None


def _repo_declares_unusable_dockerfile(repo_path):
    """True when Dockerfile* files exist but none passed the allowlist —
    an explicit failure beats silently building on the wrong base."""
    for root, dirs, names in os.walk(repo_path):
        dirs[:] = [d for d in dirs if d not in _SKIP]
        for fname in names:
            if fname == "Dockerfile" or fname.startswith("Dockerfile."):
                path = os.path.join(root, fname)
                try:
                    if not stat.S_ISREG(os.lstat(path).st_mode):
                        continue
                    with open(path, encoding="utf-8", errors="replace") as fh:
                        head = fh.readline()
                        if head.startswith("# Generated by PatchProof"):
                            continue
                        return True  # a declared (unusable) Dockerfile exists
                except OSError:
                    continue
    return False


def _detect_manifest(repo_path):
    found = deps.scan_repo(repo_path)
    for kind in ("requirements", "pyproject.toml", "package.json"):
        entry = next((e for entries in found.values() for e in entries
                      if e["manifest"] == kind), None)
        if entry:
            return kind, entry["path"]
    return None, None


def _copy(src, dst=None):
    """Dockerfile JSON-array COPY — safe for paths with spaces/metachars."""
    dst = dst or src
    return "COPY " + json.dumps([src, dst])


def _install_block(manifest_name, manifest_rel, ctx_root):
    if manifest_name == "requirements":
        return [_copy(manifest_rel),
                f"RUN pip install --no-cache-dir -r {shlex.quote(manifest_rel)}"]
    if manifest_name == "package.json":
        manifest_dir = os.path.dirname(manifest_rel)
        lockfiles = [f for f in ("package-lock.json", "npm-shrinkwrap.json",
                                 "yarn.lock", "pnpm-lock.yaml")
                     if os.path.isfile(os.path.join(ctx_root, manifest_dir, f))]
        lines = [_copy(manifest_rel)]
        lines += [_copy(os.path.join(manifest_dir, f) if manifest_dir else f)
                  for f in lockfiles]
        install = "npm ci --omit=dev" if lockfiles else "npm install --omit=dev"
        # Manifest scanning is recursive: the Node project root is the
        # manifest's directory, not necessarily the context root.
        lines.append(f"RUN cd {shlex.quote(manifest_dir)} && {install}" if manifest_dir
                     else f"RUN {install}")
        return lines
    if manifest_name == "pyproject.toml":
        # A pyproject manifest alone is not installable: source first.
        return None
    return None


_COPY_IGNORE = (".git", "venv", ".venv", "__pycache__", "node_modules",
                "data", "output")

# Evidence the entry starts its own server loop (safe to exec directly) —
# Python and Node alike.
# Server-loop evidence. Python: dedicated server-runner calls, or an explicit
# .listen() paired with a serving loop (serve_forever/IOLoop/start) — a bare
# listen() constructor alone doesn't prove the process serves. Node: ONLY an
# explicit .listen() call bound to localhost proves serving — all-interface
# binds violate the sandbox's localhost-only contract, and constructors
# without listen exit immediately.
_PY_SELF_SERVING_RE = re.compile(
    r"uvicorn\.run\(|run_app\(|app\.run\(|serve_forever\(|create_server\(|"
    r"make_server\(")
_PY_LISTEN_RE = re.compile(r"\.listen\(")
_PY_LISTEN_LOCAL_RE = re.compile(
    r"\.listen\(\s*(?:\d+|['\"][\w.]+['\"])\s*,\s*['\"]"
    r"(?:127\.0\.0\.1|localhost|::1)['\"]")
_PY_LOOP_RE = re.compile(r"serve_forever\(|IOLoop|run_forever\(|\.start\(")
_NODE_LISTEN_RE = re.compile(
    r"\.listen\(\s*(?:\d+|['\"][\w.]+['\"])\s*,\s*['\"]"
    r"(?:127\.0\.0\.1|localhost|::1)['\"]")
# Evidence the entry exposes an ASGI/WSGI application object (needs a server
# launcher — `python entry.py` would define the app and exit).
_APP_OBJECT_RE = re.compile(
    r"^\s*(\w+)\s*=\s*("
    r"FastAPI|Flask|Starlette|Quart|Sanic|Bottle|"
    r"web\.Application|aiohttp\.web\.Application)\(", re.M)


def _derive_start_command(entry, repo_path):
    """Return a runtime command that actually SERVES the app, or raise.

    A bare `[python, entry]` only works when the entry starts its own server
    loop; an entry that merely defines an ASGI/WSGI app object exits without
    serving, so it gets a uvicorn command; anything else is a hard failure
    rather than a start command we cannot prove works. Node entries must show
    a listener/server loop too — console-only scripts exit immediately.
    """
    runner, ext = ("python", ".py") if entry.endswith(".py") else ("node", ".js")
    try:
        with open(os.path.join(repo_path, entry), encoding="utf-8",
                  errors="replace") as fh:
            text = fh.read()
    except OSError:
        text = ""
    if runner == "python":
        if _PY_LISTEN_RE.search(text):
            # A .listen() must bind loopback explicitly (tornado-style
            # binds default to all interfaces); runners like uvicorn.run/
            # run_app/serve_forever default to 127.0.0.1 safely.
            self_serving = (_PY_LISTEN_LOCAL_RE.search(text)
                            and _PY_LOOP_RE.search(text))
        else:
            self_serving = _PY_SELF_SERVING_RE.search(text)
    else:
        self_serving = _NODE_LISTEN_RE.search(text)
    if not self_serving:
        if runner == "python" and _PY_LISTEN_RE.search(text) and \
                not _PY_LISTEN_LOCAL_RE.search(text):
            raise ValueError(
                f"cannot prove a safe serving command for {entry}: a "
                f".listen() call exists but does not bind 127.0.0.1/"
                f"localhost — sandbox services must bind loopback only; "
                f"fix the bind or supply the startup command explicitly")
        if runner == "node":
            if ".listen(" in text:
                raise ValueError(
                    f"cannot prove a safe serving command for {entry}: a "
                    f".listen() call exists but does not bind 127.0.0.1/"
                    f"localhost — sandbox services must bind loopback only; "
                    f"fix the bind or supply the startup command explicitly")
            raise ValueError(
                f"cannot prove a serving command for {entry}: the script "
                f"shows no localhost-bound listener (listen(3000, "
                f"'127.0.0.1')); supply the startup command explicitly")
        m = _APP_OBJECT_RE.search(text)
        if m:
            module = entry[:-len(ext)].replace(os.sep, ".").replace("/", ".")
            module = re.sub(r"\.__init__$", "", module)
            return ["uvicorn", f"{module}:{m.group(1)}",
                    "--host", "127.0.0.1", "--port", "8000"]
        raise ValueError(
            f"cannot prove a serving command for {entry}: it neither starts a "
            f"server loop nor exposes a recognized ASGI/WSGI app object; supply "
            f"the startup command explicitly instead of a start that exits")
    return [runner, entry]


def _write_file(path, content, force):
    if os.path.islink(path):
        # A repo-controlled symlink at the target name would be followed on
        # write (truncating its target, possibly outside the repo) — refuse.
        raise RuntimeError(
            f"{path} is a symlink; refusing to write through it")
    if os.path.exists(path) and not force:
        raise FileExistsError(
            f"{path} already exists; refusing to overwrite target files "
            f"(pass --force to replace explicitly)")
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(content)


def generate(repo_path, out_dir=None, force=False):
    """Build a sandbox-ready context at out_dir. NEVER touches the repo's
    own Dockerfile*: the working definition is always written as
    `Dockerfile.patchproof` (built via sandbox_build's -f support), so
    repo files are never overwritten and suffixed variants work.

    Source selection:
      - declared + allowlisted final-stage base  -> reuse VERBATIM (its RUN
        steps — apk/apt build tooling — make pinned deps installable);
        the image's WORKDIR is recorded and the start command runs there.
      - declared but unusable                    -> synthesize the generic
        default (fallback; no ValueError).
      - none declared                            -> synthesize.
    """
    repo_path = os.path.abspath(repo_path)
    out_dir = os.path.abspath(out_dir) if out_dir else repo_path

    if out_dir != repo_path:
        if os.path.exists(out_dir) and os.listdir(out_dir):
            raise FileExistsError(f"{out_dir} is not empty; refusing to mix contexts")
        shutil.copytree(repo_path, out_dir,
                        ignore=shutil.ignore_patterns(*_COPY_IGNORE),
                        dirs_exist_ok=True)

    entry = _find_entry(repo_path)
    if not entry:
        raise ValueError(
            f"no runnable application entry detected in {repo_path} "
            f"(looked for {', '.join(_ENTRY_CANDIDATES)}); supply the entry "
            f"explicitly instead of generating a Dockerfile that cannot start")
    manifest_name, manifest_path = _detect_manifest(repo_path)
    is_py = entry.endswith(".py")
    runner = "python" if is_py else "node"
    start_command = _derive_start_command(entry, repo_path)
    detected = _detect_base_image(repo_path, "py" if is_py else "js")

    lines = []
    workdir = "/srv"
    if detected:
        base, declared_rel = detected
        # Verbatim reuse: the repo's own RUN steps (apk/apt build tooling)
        # are exactly what make its pinned dependencies installable.
        with open(os.path.join(repo_path, declared_rel), encoding="utf-8") as fh:
            declared_content = fh.read()
        content_lines = declared_content.rstrip("\n").split("\n")
        # Parser directives (# syntax=/# escape=) must stay at the very top:
        # hoist leading comment/directive lines ahead of our marker.
        directives = []
        while content_lines and content_lines[0].lstrip().startswith("#"):
            directives.append(content_lines.pop(0))
        lines += directives
        lines.append(_GENERATED_MARKER)
        lines += content_lines
        # WORKDIR is resolved within the FINAL stage only, following
        # Docker's relative-path semantics; variable workdirs are
        # unresolvable here and keep the previous value.
        in_final = False
        resolved = "/srv"
        for line in content_lines:
            stripped = line.strip()
            if stripped.upper().startswith("FROM"):
                in_final = True
                resolved = "/srv"  # each stage starts from its base default
                continue
            if not in_final or not stripped.upper().startswith("WORKDIR"):
                continue
            val = stripped.split(None, 1)[1].strip().strip('"')
            if "${" in val:
                continue
            resolved = val if val.startswith("/") else \
                os.path.join(resolved, val)
        workdir = resolved
        # A repo ENTRYPOINT would turn our CMD into its arguments — clear it
        # so the validated start command is the container's executable.
        if any(l.strip().upper().startswith("ENTRYPOINT")
               for l in content_lines):
            lines.append("ENTRYPOINT []")
        source = "repo-dockerfile"
    else:
        base = "python:3.11-slim" if is_py else "node:20-slim"
        source = "synthesized"
        lines.append(_GENERATED_MARKER)
        lines.append(f"FROM {base}")
        lines.append("WORKDIR /srv")
        if start_command[0] == "uvicorn":
            # App-object derivation emits a uvicorn launch, but the repo's
            # own requirements may not include it. Install BEFORE the repo
            # deps so a pinned uvicorn (uvicorn==0.29.0) re-asserts itself
            # during `pip install -r requirements.txt` and the vulnerable
            # environment stays intact.
            lines.append('RUN pip install --no-cache-dir "uvicorn>=0.30"')
        if manifest_path and manifest_name == "pyproject.toml":
            lines += ["COPY . /srv", "RUN pip install --no-cache-dir ."]
        else:
            install_lines = (_install_block(manifest_name, manifest_path,
                                            out_dir) if manifest_path else [])
            lines += install_lines + ["COPY . /srv"]

    if workdir != "/srv":
        # sandbox_exec always starts in /srv; the reused image's app lives
        # at its own WORKDIR, so the start command cd's there first.
        cd_cmd = f"cd {shlex.quote(workdir)} && " + shlex.join(start_command)
        lines.append(f"CMD {json.dumps(['sh', '-c', cd_cmd])}")
        effective_start = ["sh", "-c", f"cd {shlex.quote(workdir)} && "
                                        + shlex.join(start_command)]
    else:
        lines.append(f"CMD {json.dumps(start_command)}")
        effective_start = start_command

    _write_file(os.path.join(out_dir, "Dockerfile.patchproof"),
                "\n".join(lines) + "\n", force)
    _write_file(os.path.join(out_dir, ".dockerignore"),
                "\n".join((".git", ".env", ".env.*", "*.pem", "*.key", "*.p12",
                            "*.pfx", "id_rsa*", ".aws", ".ssh", ".npmrc",
                            ".pypirc", "credentials*", "*.credentials",
                            "venv", ".venv", "__pycache__", "node_modules",
                            "data", "output")) + "\n", force)

    # The sandbox start command overrides the Dockerfile CMD, so persist the
    # validated startup command for the reproducer to consume (it cannot
    # assume `uvicorn main:app` for arbitrary repos).
    context_record = {
        "dockerfile": os.path.join(out_dir, "Dockerfile.patchproof"),
        "dockerfile_name": "Dockerfile.patchproof",
        "base_image": base,
        "entry": entry,
        "workdir": workdir,
        "start_command": effective_start,
        "dependency_manifest": manifest_path,
        "build_context": out_dir,
        "source": source,
        "generated": True,
    }
    _write_file(os.path.join(out_dir, "patchproof-build-context.json"),
                json.dumps(context_record, indent=2, ensure_ascii=False) + "\n",
                force)

    return context_record


def main(argv=None):
    parser = argparse.ArgumentParser(description="PatchProof build-context generator")
    parser.add_argument("repo_path", help="path to the target repository")
    parser.add_argument("--out", help="write a complete build context here (default: repo path)")
    parser.add_argument("--force", action="store_true",
                        help="replace an existing generated Dockerfile/.dockerignore")
    args = parser.parse_args(argv)

    result = generate(args.repo_path, args.out, args.force)
    print(json.dumps(result, indent=2, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    sys.exit(main())
