#!/usr/bin/env python3
"""Build-context generator: version-matched minimal sandbox image.

Synthesizes `Dockerfile.patchproof` — built via sandbox_build's -f
argument — from the repo's OWN runtime version, keeping the sandbox base
as small as possible:

  - official `python:<ver>-slim` / `node:<ver>-slim` base, version detected
    from the repo itself (declared Dockerfile tags, .python-version /
    runtime.txt, package.json engines, python_requires); falls back to the
    tool default when nothing declares a version
  - our own uniform install lines only — repository-controlled Dockerfile
    instructions (RUN/ADD/ENTRYPOINT/...) NEVER execute at build time
    (ADR-017)

The repo's own Dockerfile* files are never read as build definitions and
never overwritten. Our output carries a marker so stale artifacts from
earlier runs are never mistaken for a repo declaration.
"""

import argparse
import itertools
import json
import os
import re
import shlex
import shutil
import stat
import sys

if __package__ in (None, ""):  # direct-file execution: make the package importable
    sys.path.insert(0, os.path.dirname(os.path.dirname(
        os.path.dirname(os.path.abspath(__file__)))))
    from agent.analyzer import deps
else:
    from . import deps

_ENTRY_CANDIDATES = ("main.py", "app.py", "run.py", "server.py", "wsgi.py",
                     "manage.py", "index.js", "server.js", "app.js", "main.js")
_SKIP = deps._SKIP_PARTS + ("tests", "test", ".github", "dist", "build",
                            "static", "assets", "vendor", "public")

_GENERATED_MARKER = "# Generated by PatchProof gen_context (safe to delete)."

_DEFAULT_PY = "3.11"
_DEFAULT_NODE = "20"

# Version tokens we accept from a declared base tag: python:3.8-slim → 3.8,
# node:20-alpine → 20, python:alpine3.8 → 3.8 (alpine3.Y maps to 3.Y).
_TAG_PY_VERSION_RE = re.compile(r"^(?:py)?-?alpine?(\d+)\.(\d+)", re.I)
_TAG_PLAIN_VERSION_RE = re.compile(r"^(\d+)(?:\.(\d+))?")
_PY_VERSION_FILE_RE = re.compile(r"^(?:python\s*)?(\d+)\.(\d+)", re.I)
_PY_REQUIRES_RE = re.compile(r">=\s*(\d+)\.(\d+)")


def _write_file(path, content, force):
    if os.path.islink(path):
        # A repo-controlled symlink at the target name would be followed on
        # write (truncating its target, possibly outside the repo) — refuse.
        raise RuntimeError(
            f"{path} is a symlink; refusing to write through it")
    if os.path.exists(path) and not force:
        raise FileExistsError(
            f"{path} already exists; refusing to overwrite target files "
            f"(pass --force to replace explicitly)")
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(content)


def _find_entry(repo_path):
    for root, dirs, files in os.walk(repo_path):
        dirs[:] = [d for d in dirs if d not in _SKIP]
        for fname in files:
            if fname in _ENTRY_CANDIDATES:
                return os.path.relpath(os.path.join(root, fname), repo_path)
    return None


def _dockerfile_from_tags(repo_path):
    """Version hints from declared Dockerfile* FROM tags, in FILE priority
    order (canonical Dockerfile first, then runtime-suffixed variants) and,
    within a file, the LAST FROM — the runtime stage's — tag. Our own
    generated artifacts are marker-skipped; registry-qualified official
    names (docker.io/library/python) count; repo-controlled symlinks and
    non-regular files are skipped."""
    preferred = ["Dockerfile", "Dockerfile.app", "Dockerfile.web",
                 "Dockerfile.prod", "Dockerfile.api", "Dockerfile.server"]
    files = []
    for root, dirs, names in os.walk(repo_path):
        dirs[:] = [d for d in dirs if d not in _SKIP]
        for fname in names:
            if fname == "Dockerfile" or fname.startswith("Dockerfile."):
                path = os.path.join(root, fname)
                try:
                    if not stat.S_ISREG(os.lstat(path).st_mode):
                        continue
                except OSError:
                    continue
                rel = os.path.relpath(path, repo_path)
                prio = preferred.index(fname) if fname in preferred else 99
                files.append((prio, rel))
    files.sort()
    hints = []
    for _prio, rel in files:
        path = os.path.join(repo_path, rel)
        try:
            with open(path, encoding="utf-8", errors="replace") as fh:
                head = fh.readline()
                if head.startswith("# Generated by PatchProof"):
                    continue  # our own earlier artifact — not a repo hint
                tag = None
                for line in itertools.chain((head,), fh):
                    parts = line.split()
                    if not parts or parts[0].upper() != "FROM":
                        continue
                    real = [p for p in parts[1:] if not p.startswith("--")]
                    img = real[0] if real else ""
                    if not img or "${" in img:
                        continue
                    short = img.split("/")[-1]  # registry/host-qualified OK
                    name = short.split(":", 1)[0].split("@", 1)[0]
                    if name not in ("python", "node"):
                        continue
                    tag = short.split(":", 1)[1] if ":" in short else ""
                    # keep scanning: the LAST FROM is the runtime stage
                if tag is not None:
                    hints.append((short.split(":")[0].split("@")[0]
                                  if ":" in short else None, tag))
        except OSError:
            continue
    return hints


def _py_version_files(repo_path):
    """Version hints from .python-version / runtime.txt."""
    for marker in (".python-version", "runtime.txt"):
        path = os.path.join(repo_path, marker)
        if os.path.isfile(path):
            try:
                with open(path, encoding="utf-8", errors="replace") as fh:
                    text = fh.read(200)
            except OSError:
                continue
            m = _PY_VERSION_FILE_RE.search(text)
            if m:
                return f"{m.group(1)}.{m.group(2)}"
    return None


def _dec(v):
    return (v[0], v[1] - 1) if v[1] > 0 else (v[0] - 1, 11)


def _py_requires(repo_path, manifest_path=None):
    """Version SATISFYING the python_requires / requires-python FIELD
    (never a dependency's own constraint). All comparators resolve as an
    interval — order-independent; no satisfying version → None. Upper-only
    bounds select the highest satisfying version. The detected manifest is
    checked first (nested apps), then repo-root files. Commented-out
    declarations are ignored (line-anchored)."""
    spec = [
        ("setup.cfg", re.compile(r"^\s*python_requires\s*=", re.M)),
        ("setup.py", re.compile(r"^\s*python_requires\s*=", re.M)),
        ("pyproject.toml", re.compile(r"^\s*requires-python\s*=", re.M)),
    ]
    # (op?, full-version (major.minor[.patch]))
    cmp_re = re.compile(r"(>=|<=|!=|>|<|==|\^|~=)?\s*(\d+)\.(\d+)(?:\.(\d+))?")
    candidates = []
    if manifest_path and os.path.basename(manifest_path) in (
            "pyproject.toml", "setup.py", "setup.cfg"):
        candidates.append(manifest_path)
    candidates += [os.path.join(repo_path, n) for n, _ in spec]
    rx_by_name = {n: rx for n, rx in spec}
    for path in candidates:
        rx = rx_by_name.get(os.path.basename(path))
        if rx is None or not os.path.isfile(path):
            continue
        try:
            text = open(path, encoding="utf-8", errors="replace").read(20000)
        except OSError:
            continue
        m = rx.search(text)
        if not m:
            continue
        # capture the field's value as a window spanning subsequent lines so
        # multiline declarations (python_requires=(\n">=3.12"\n)) are seen
        window = text[m.start():m.start() + 256]
        comparators = cmp_re.findall(window)
        if not comparators:
            continue  # no usable constraint

        lo = hi = None
        lo_inc = hi_inc = True
        exact_patch = False
        exact = None
        for op, M, mn, pt in comparators:
            has_patch = op == "==" and pt
            v = (int(M), int(mn))
            if op == "==":
                if has_patch:
                    # exact maintenance-release pin (==3.10.5): the image layer
                    # only expresses major.minor, and Requires-Python exact
                    # matching rejects a differing interpreter -> no hint
                    # (fail open; pip enforces honestly at install time)
                    exact_patch = True
                elif not exact_patch:
                    exact = v
            elif op == "!=":
                continue  # exclusions: not representable as an interval
            elif op == ">":
                lo = v if lo is None or v > lo else lo
                lo_inc = False
            elif op == ">=":
                lo = v if lo is None or v > lo else lo
            elif op == "<":
                hi = v if hi is None or v < hi else hi
                hi_inc = False
            elif op == "<=":
                hi = v if hi is None or v < hi else hi
            else:  # ^ ~= : floor
                lo = v if lo is None or v > lo else lo

        if exact_patch:
            return None  # exact maintenance pin not expressible as an image tag
        if exact is not None:
            if lo is not None and (exact < lo or (exact == lo and not lo_inc)):
                return None
            if hi is not None and (exact > hi or (exact == hi and not hi_inc)):
                return None
            return f"{exact[0]}.{exact[1]}"
        if lo is None:
            if hi is None:
                return None
            cand = hi if hi_inc else _dec(hi)
        else:
            cand = lo if lo_inc else (lo[0], lo[1] + 1)
            if hi is not None:
                hi_eff = hi if hi_inc else _dec(hi)
                if cand > hi_eff:
                    return None  # constraints conflict → no hint
        if cand[0] < 3:
            return None
        return f"{cand[0]}.{cand[1]}"
    return None


def _node_engines(manifest_path):
    """Node version hint from the package.json `engines.node` field
    (operator-aware: upper bounds/exclusions name no usable runtime;
    node image tags are major-only)."""
    if not manifest_path or not manifest_path.endswith("package.json"):
        return None
    try:
        with open(manifest_path, encoding="utf-8") as fh:
            engines = (json.load(fh).get("engines") or {})
        raw = engines.get("node") or ""
    except (OSError, ValueError):
        return None
    m = re.search(r"(>=|<=|!=|>|<|\^|~=)?\s*(\d+)", raw)
    if not m:
        return None
    if m.group(1) in ("<", "<=", "!="):
        return None
    return m.group(2)


def _tag_version_for(lang, tag_pairs):
    for t_lang, tag in tag_pairs:
        if t_lang != lang or not tag:
            continue
        if lang == "python":
            m = _TAG_PLAIN_VERSION_RE.match(tag)
            if m:
                return m.group(1) if not m.group(2) \
                    else f"{m.group(1)}.{m.group(2)}"
            m = _TAG_PY_VERSION_RE.match(tag)
            if m:  # alpine3.Y maps to python 3.Y
                return f"3.{m.group(2)}"
        else:
            m = _TAG_PLAIN_VERSION_RE.match(tag)
            if m:
                return m.group(1) if not m.group(2) else f"{m.group(1)}.{m.group(2)}"
    return None


def _pick_version(hints, default):
    """First concrete hint wins — the documented precedence (declared
    Dockerfile runtime tag, then version file/engines, then floors). No
    max(): a higher unrelated floor must not override an exact pin."""
    for h in hints:
        if h:
            return h
    return default


def detect_runtime_version(repo_path, lang, manifest_path=None):
    """Return the major[.minor] version the repo actually runs, or the
    tool default. Precedence: first concrete hint wins in this order —
    declared Dockerfile runtime-stage tag, .python-version / runtime.txt
    (python) or package.json engines (node), python_requires."""
    if lang == "py":
        hints = [_tag_version_for("python",
                                  _dockerfile_from_tags(repo_path)),
                 _py_version_files(repo_path),
                 _py_requires(repo_path, manifest_path)]
    else:
        hints = [_tag_version_for("node",
                                  _dockerfile_from_tags(repo_path)),
                 _node_engines(manifest_path)
                 or _node_engines(os.path.join(repo_path, "package.json"))]
    return _pick_version(hints, _DEFAULT_ + "_X" if False else
                         (_DEFAULT_PY if lang == "py" else _DEFAULT_NODE))


def _final_workdir(dockerfile_path):
    """Final-stage WORKDIR of a Dockerfile (stage-aware, relative-chained,
    variable workdirs unresolved → None); None when absent."""
    if not dockerfile_path or not os.path.isfile(dockerfile_path):
        return None
    stage_workdirs = {}
    current = "/"
    current_name = None
    last_was_var = False
    try:
        with open(dockerfile_path, encoding="utf-8", errors="replace") as fh:
            for line in fh:
                parts = line.split()
                if parts and parts[0].upper() == "FROM":
                    if current_name:
                        stage_workdirs[current_name] = current
                    real = [p for p in parts[1:] if not p.startswith("--")]
                    img = real[0] if real else ""
                    current_name = real[2] if len(real) > 2 \
                        and real[1].upper() == "AS" else None
                    if img in stage_workdirs:
                        current = stage_workdirs[img]
                    elif "$" not in img:
                        current = "/"
                    last_was_var = False
                    continue
                if not parts or parts[0].upper() != "WORKDIR":
                    continue
                val = parts[1].strip('"') if len(parts) > 1 else ""
                if "$" in val:
                    last_was_var = True
                    continue
                last_was_var = False
                current = val if val.startswith("/") else \
                    os.path.join(current, val)
        if current_name:
            stage_workdirs[current_name] = current
    except OSError:
        return None
    # A trailing variable WORKDIR is unresolvable — record None (the
    # skill/prompt documents the probe procedure) instead of a stale path.
    return None if last_was_var else current


def _official_base_name(img):
    """True iff `img` is a STRICT official python/node image reference:
    python, node, library/python, library/node, or docker.io/library/... —
    each with an optional non-empty `:<tag>`. Digest-qualified references
    (`@sha256:...`), empty tags (`python:`), and any foreign/registry/
    organization-qualified name whose last segment merely equals python/node
    are rejected (ADR-016: repo content stays inert data; ADR-017 tier-2
    keeps the strict official-base restriction)."""
    if "@" in img:
        return False  # digest-qualified references are never allowed
    if img.count(":") > 1:
        return False  # malformed reference
    repo, _, tag = img.partition(":")
    if tag == "" and ":" in img:
        return False  # empty tag (`python:`) is not a valid official base
    segs = [x for x in repo.split("/") if x]
    if not segs:
        return False
    if segs[0] == "docker.io":
        segs = segs[1:]
    if len(segs) == 2 and segs[0] == "library":
        segs = [segs[1]]
    return len(segs) == 1 and segs[0] in ("python", "node")


def _first_declared_dockerfile(repo_path):
    """Name of the repo's own declared runtime Dockerfile (priority order)
    for explicit build-failure escalation — or None. Only a Dockerfile whose
    runtime (last) FROM base is a STRICT allowlisted official `python`/`node`
    image qualifies (ADR-016: repo content stays inert data; ADR-017 tier-2
    keeps the strict official-base restriction rather than executing
    arbitrary repo-controlled base images). Foreign/registry-qualified
    pseudo-official names and variable FROM are rejected."""
    preferred = ["Dockerfile", "Dockerfile.app", "Dockerfile.web",
                 "Dockerfile.prod", "Dockerfile.api", "Dockerfile.server"]
    files = []
    for root, dirs, names in os.walk(repo_path):
        dirs[:] = [d for d in dirs if d not in _SKIP]
        for fname in names:
            if fname == "Dockerfile" or fname.startswith("Dockerfile."):
                path = os.path.join(root, fname)
                try:
                    if not stat.S_ISREG(os.lstat(path).st_mode):
                        continue
                    with open(path, encoding="utf-8",
                              errors="replace") as fh:
                        lines = fh.readlines()
                except OSError:
                    continue  # unreadable fallback candidate is skipped
                if lines and lines[0].startswith("# Generated by PatchProof"):
                    continue  # our own earlier artifact
                # runtime (last) FROM must be an allowlisted official base
                allowlisted = False
                for line in lines:
                    parts = line.split()
                    if not parts or parts[0].upper() != "FROM":
                        continue
                    real = [p for p in parts[1:] if not p.startswith("--")]
                    img = real[0] if real else ""
                    if "${" in img or "$" in img:
                        allowlisted = False  # variable base: not verifiable
                        continue
                    allowlisted = _official_base_name(img)
                if allowlisted:
                    files.append(os.path.relpath(path, repo_path))
    files.sort(key=lambda f: (preferred.index(os.path.basename(f))
                              if os.path.basename(f) in preferred else 99, f))
    return files[0] if files else None


def _detect_manifest(repo_path):
    found = deps.scan_repo(repo_path)
    for kind in ("requirements", "pyproject.toml", "package.json"):
        entry = next((e for entries in found.values() for e in entries
                      if e["manifest"] == kind), None)
        if entry:
            return kind, entry["path"]
    return None, None


def _copy(src, dst=None):
    """Dockerfile JSON-array COPY — safe for paths with spaces/metachars."""
    dst = dst or src
    return "COPY " + json.dumps([src, dst])


def _install_block(manifest_name, manifest_rel, ctx_root):
    if manifest_name == "requirements":
        return [_copy(manifest_rel),
                f"RUN pip install --no-cache-dir -r {shlex.quote(manifest_rel)}"]
    if manifest_name == "package.json":
        manifest_dir = os.path.dirname(manifest_rel)
        lockfiles = [f for f in ("package-lock.json", "npm-shrinkwrap.json",
                                 "yarn.lock", "pnpm-lock.yaml")
                     if os.path.isfile(os.path.join(ctx_root, manifest_dir, f))]
        lines = [_copy(manifest_rel)]
        lines += [_copy(os.path.join(manifest_dir, f) if manifest_dir else f)
                  for f in lockfiles]
        install = "npm ci --omit=dev" if lockfiles else "npm install --omit=dev"
        # Manifest scanning is recursive: the Node project root is the
        # manifest's directory, not necessarily the context root.
        lines.append(f"RUN cd {shlex.quote(manifest_dir)} && {install}" if manifest_dir
                     else f"RUN {install}")
        return lines
    if manifest_name == "pyproject.toml":
        # A pyproject manifest alone is not installable: source first.
        return None
    return None


_COPY_IGNORE = (".git", "venv", ".venv", "__pycache__", "node_modules",
                "data", "output")

# Evidence the entry starts its own server loop (safe to exec directly) —
# Python and Node alike.
_PY_SELF_SERVING_RE = re.compile(
    r"uvicorn\.run\(|run_app\(|app\.run\(|serve_forever\(|create_server\(|"
    r"make_server\(")
_PY_LISTEN_RE = re.compile(r"\.listen\(")
_PY_LISTEN_LOCAL_RE = re.compile(
    r"\.listen\(\s*(?:\d+|['\"][\w.]+['\"])\s*,\s*['\"]"
    r"(?:127\.0\.0\.1|localhost|::1)['\"]")
_PY_LOOP_RE = re.compile(r"serve_forever\(|IOLoop|run_forever\(|\.start\(")
_NODE_LISTEN_RE = re.compile(
    r"\.listen\(\s*(?:\d+|['\"][\w.]+['\"])\s*,\s*['\"]"
    r"(?:127\.0\.0\.1|localhost|::1)['\"]")
# Evidence the entry exposes an ASGI/WSGI application object (needs a server
# launcher — `python entry.py` would define the app and exit).
_APP_OBJECT_RE = re.compile(
    r"^\s*(\w+)\s*=\s*("
    r"FastAPI|Flask|Starlette|Quart|Sanic|Bottle|"
    r"web\.Application|aiohttp\.web\.Application)\(", re.M)


def _derive_start_command(entry, repo_path):
    """Return a runtime command that actually SERVES the app, or raise.

    A bare `[python, entry]` only works when the entry starts its own server
    loop; an entry that merely defines an ASGI/WSGI app object exits without
    serving, so it gets a uvicorn command; anything else is a hard failure
    rather than a start command we cannot prove works. Node entries must show
    a listener/server loop too — console-only scripts exit immediately.
    """
    runner = "python" if entry.endswith(".py") else "node"
    try:
        with open(os.path.join(repo_path, entry), encoding="utf-8",
                  errors="replace") as fh:
            text = fh.read()
    except OSError:
        text = ""
    if runner == "python":
        if _PY_LISTEN_RE.search(text):
            # A .listen() must bind loopback explicitly (tornado-style
            # binds default to all interfaces); runners like uvicorn.run/
            # run_app/serve_forever default to 127.0.0.1 safely.
            self_serving = (_PY_LISTEN_LOCAL_RE.search(text)
                            and _PY_LOOP_RE.search(text))
        else:
            self_serving = _PY_SELF_SERVING_RE.search(text)
    else:
        self_serving = _NODE_LISTEN_RE.search(text)
    if not self_serving:
        if runner == "python" and _PY_LISTEN_RE.search(text) and \
                not _PY_LISTEN_LOCAL_RE.search(text):
            raise ValueError(
                f"cannot prove a safe serving command for {entry}: a "
                f".listen() call exists but does not bind 127.0.0.1/"
                f"localhost — sandbox services must bind loopback only; "
                f"fix the bind or supply the startup command explicitly")
        if runner == "node":
            if ".listen(" in text:
                raise ValueError(
                    f"cannot prove a safe serving command for {entry}: a "
                    f".listen() call exists but does not bind 127.0.0.1/"
                    f"localhost — sandbox services must bind loopback only; "
                    f"fix the bind or supply the startup command explicitly")
            raise ValueError(
                f"cannot prove a serving command for {entry}: the script "
                f"shows no localhost-bound listener (listen(3000, "
                f"'127.0.0.1')); supply the startup command explicitly")
        m = _APP_OBJECT_RE.search(text)
        if m:
            module = entry[:-3].replace(os.sep, ".").replace("/", ".")
            module = re.sub(r"\.__init__$", "", module)
            return ["uvicorn", f"{module}:{m.group(1)}",
                    "--host", "127.0.0.1", "--port", "8000"]
        raise ValueError(
            f"cannot prove a serving command for {entry}: it neither starts a "
            f"server loop nor exposes a recognized ASGI/WSGI app object; supply "
            f"the startup command explicitly instead of a start that exits")
    return [runner, entry]


def generate(repo_path, out_dir=None, force=False):
    """Write a minimal, version-matched `Dockerfile.patchproof` into the
    build context. The repo's own Dockerfile* files are never overwritten
    and never executed."""
    repo_path = os.path.abspath(repo_path)
    out_dir = os.path.abspath(out_dir) if out_dir else repo_path

    if out_dir != repo_path:
        if os.path.exists(out_dir) and os.listdir(out_dir):
            raise FileExistsError(f"{out_dir} is not empty; refusing to mix contexts")
        shutil.copytree(repo_path, out_dir,
                        ignore=shutil.ignore_patterns(*_COPY_IGNORE),
                        dirs_exist_ok=True)

    entry = _find_entry(repo_path)
    if not entry:
        raise ValueError(
            f"no runnable application entry detected in {repo_path} "
            f"(looked for {', '.join(_ENTRY_CANDIDATES)}); supply the entry "
            f"explicitly instead of generating a Dockerfile that cannot start")
    manifest_name, manifest_path = _detect_manifest(repo_path)
    is_py = entry.endswith(".py")
    runner = "python" if is_py else "node"
    start_command = _derive_start_command(entry, repo_path)
    version = detect_runtime_version(repo_path, "py" if is_py else "js")
    base = (f"python:{version}-slim" if is_py else f"node:{version}-slim")

    lines = [_GENERATED_MARKER, f"FROM {base}", "WORKDIR /srv"]
    # Compiled dependencies (psycopg2, cffi, ...) need tooling the slim
    # base lacks — install a uniform, per-language build-tools layer BEFORE
    # the repo deps. Repo deps that pin their own versions re-assert during
    # the install, so the vulnerable environment stays intact.
    if manifest_path and is_py:
        lines.append(
            "RUN apt-get update && apt-get install -y --no-install-recommends "
            "gcc python3-dev libpq-dev libffi-dev "
            "&& rm -rf /var/lib/apt/lists/*")
    if start_command[0] == "uvicorn":
        # App-object derivation emits a uvicorn launch, but the repo's own
        # requirements may not include it. Install BEFORE the repo deps so
        # a pinned uvicorn (uvicorn==0.29.0) re-asserts itself during
        # `pip install -r requirements.txt` and the vulnerable environment
        # stays intact.
        lines.append('RUN pip install --no-cache-dir "uvicorn>=0.30"')
    if manifest_path and manifest_name == "pyproject.toml":
        lines += ["COPY . /srv", "RUN pip install --no-cache-dir ."]
    else:
        install_lines = (_install_block(manifest_name, manifest_path,
                                        out_dir) if manifest_path else [])
        lines += install_lines + ["COPY . /srv"]
    lines.append(f"CMD {json.dumps(start_command)}")

    _write_file(os.path.join(out_dir, "Dockerfile.patchproof"),
                "\n".join(lines) + "\n", force)
    _write_file(os.path.join(out_dir, ".dockerignore"),
                "\n".join((".git", ".env", ".env.*", "*.pem", "*.key", "*.p12",
                           "*.pfx", "id_rsa*", ".aws", ".ssh", ".npmrc",
                           ".pypirc", "credentials*", "*.credentials",
                           "venv", ".venv", "__pycache__", "node_modules",
                           "data", "output")) + "\n", force)

    # The sandbox start command overrides the Dockerfile CMD, so persist the
    # validated startup command for the reproducer to consume (it cannot
    # assume `uvicorn main:app` for arbitrary repos).
    # Two-tier build (ADR-017): the synthesized minimal definition is the
    # primary; if its install fails (legacy compiled deps), the reproducer
    # escalates to the repo's OWN declared Dockerfile via the -f argument —
    # an explicit, documented escalation of the build-time trust boundary.
    fallback = _first_declared_dockerfile(repo_path)
    fallback_workdir = _final_workdir(
        os.path.join(repo_path, fallback)) if fallback else None
    context_record = {
        "dockerfile": os.path.join(out_dir, "Dockerfile.patchproof"),
        "dockerfile_name": "Dockerfile.patchproof",
        "fallback_dockerfile": fallback,
        "fallback_workdir": fallback_workdir,
        "base_image": base,
        "runtime_version": version,
        "workdir": "/srv",
        "entry": entry,
        "start_command": start_command,
        "dependency_manifest": manifest_path,
        "build_context": out_dir,
        "source": "synthesized",
        "generated": True,
    }
    _write_file(os.path.join(out_dir, "patchproof-build-context.json"),
                json.dumps(context_record, indent=2, ensure_ascii=False) + "\n",
                force)

    return context_record


def main(argv=None):
    parser = argparse.ArgumentParser(description="PatchProof build-context generator")
    parser.add_argument("repo_path", help="path to the target repository")
    parser.add_argument("--out", help="write a complete build context here (default: repo path)")
    parser.add_argument("--force", action="store_true",
                        help="replace an existing generated Dockerfile.patchproof/.dockerignore")
    args = parser.parse_args(argv)

    result = generate(args.repo_path, args.out, args.force)
    print(json.dumps(result, indent=2, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    sys.exit(main())
