#!/usr/bin/env python3
"""Build-context generator: version-matched minimal sandbox image.

Synthesizes `Dockerfile.patchproof` — built via sandbox_build's -f
argument — from the repo's OWN runtime version, keeping the sandbox base
as small as possible:

  - official `python:<ver>-slim` / `node:<ver>-slim` base, version detected
    from the repo itself (declared Dockerfile tags, .python-version /
    runtime.txt, package.json engines, python_requires); falls back to the
    tool default when nothing declares a version
  - our own uniform install lines only — repository-controlled Dockerfile
    instructions (RUN/ADD/ENTRYPOINT/...) NEVER execute at build time
    (ADR-017)

The repo's own Dockerfile* files are never read as build definitions and
never overwritten. Our output carries a marker so stale artifacts from
earlier runs are never mistaken for a repo declaration.
"""

import argparse
import itertools
import json
import os
import re
import shlex
import shutil
import stat
import sys

if __package__ in (None, ""):  # direct-file execution: make the package importable
    sys.path.insert(0, os.path.dirname(os.path.dirname(
        os.path.dirname(os.path.abspath(__file__)))))
    from agent.analyzer import deps
else:
    from . import deps

_ENTRY_CANDIDATES = ("main.py", "app.py", "run.py", "server.py", "wsgi.py",
                     "manage.py", "index.js", "server.js", "app.js", "main.js")
_SKIP = deps._SKIP_PARTS + ("tests", "test", ".github", "dist", "build",
                            "static", "assets", "vendor", "public")

_GENERATED_MARKER = "# Generated by PatchProof gen_context (safe to delete)."

_DEFAULT_PY = "3.11"
_DEFAULT_NODE = "20"

# Version tokens we accept from a declared base tag: python:3.8-slim → 3.8,
# node:20-alpine → 20, python:alpine3.8 → 3.8 (alpine3.Y maps to 3.Y).
_TAG_PY_VERSION_RE = re.compile(r"^(?:py)?-?alpine?(\d+)\.(\d+)", re.I)
_TAG_PLAIN_VERSION_RE = re.compile(r"^(\d+)(?:\.(\d+))?")
_PY_VERSION_FILE_RE = re.compile(r"^(?:python\s*)?(\d+)\.(\d+)", re.I)
_PY_REQUIRES_RE = re.compile(r">=\s*(\d+)\.(\d+)")


def _write_file(path, content, force):
    if os.path.islink(path):
        # A repo-controlled symlink at the target name would be followed on
        # write (truncating its target, possibly outside the repo) — refuse.
        raise RuntimeError(
            f"{path} is a symlink; refusing to write through it")
    if os.path.exists(path) and not force:
        raise FileExistsError(
            f"{path} already exists; refusing to overwrite target files "
            f"(pass --force to replace explicitly)")
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(content)


def _find_entry(repo_path):
    for root, dirs, files in os.walk(repo_path):
        dirs[:] = [d for d in dirs if d not in _SKIP]
        for fname in files:
            if fname in _ENTRY_CANDIDATES:
                return os.path.relpath(os.path.join(root, fname), repo_path)
    return None


def _dockerfile_from_tags(repo_path):
    """Version hints from declared Dockerfile* FROM tags (never followed if
    not regular files — repo-controlled symlinks/FIFOs are skipped)."""
    versions = []
    for root, dirs, files in os.walk(repo_path):
        dirs[:] = [d for d in dirs if d not in _SKIP]
        for fname in files:
            if not (fname == "Dockerfile" or fname.startswith("Dockerfile.")):
                continue
            path = os.path.join(root, fname)
            try:
                if not stat.S_ISREG(os.lstat(path).st_mode):
                    continue
                with open(path, encoding="utf-8", errors="replace") as fh:
                    for line in itertools.chain((), fh):
                        parts = line.split()
                        if not parts or parts[0].upper() != "FROM":
                            continue
                        img = next((p for p in parts[1:]
                                    if not p.startswith("--")), None)
                        if not img or img.split("/")[0].split(":")[0] \
                                not in ("python", "node"):
                            continue
                        lang = "python" if img.startswith("python") else "node"
                        tag = img.split(":", 1)[1] if ":" in img else ""
                        versions.append((lang, tag))
            except OSError:
                continue
    return versions


def _py_version_files(repo_path):
    """Version hints from .python-version / runtime.txt."""
    for marker in (".python-version", "runtime.txt"):
        path = os.path.join(repo_path, marker)
        if os.path.isfile(path):
            try:
                with open(path, encoding="utf-8", errors="replace") as fh:
                    text = fh.read(200)
            except OSError:
                continue
            m = _PY_VERSION_FILE_RE.search(text)
            if m:
                return f"{m.group(1)}.{m.group(2)}"
    return None


def _py_requires(repo_path):
    """Version floor from setup.py/pyproject python_requires (best effort)."""
    for name in ("setup.py", "setup.cfg", "pyproject.toml"):
        path = os.path.join(repo_path, name)
        if not os.path.isfile(path):
            continue
        try:
            with open(path, encoding="utf-8", errors="replace") as fh:
                m = _PY_REQUIRES_RE.search(fh.read(20000))
        except OSError:
            continue
        if m:
            return f"{m.group(1)}.{m.group(2)}"
    return None


def _node_engines(repo_path):
    path = os.path.join(repo_path, "package.json")
    if not os.path.isfile(path):
        return None
    try:
        with open(path, encoding="utf-8") as fh:
            engines = (json.load(fh).get("engines") or {})
        raw = engines.get("node") or ""
    except (OSError, ValueError):
        return None
    m = re.search(r"(\d+)(?:\.(\d+))?", raw)
    if m:
        return m.group(1) if not m.group(2) else f"{m.group(1)}.{m.group(2)}"
    return None


def _pick_version(hints, default):
    """First concrete hint wins; ties resolved by simple highest-version."""
    usable = [h for h in hints if h]
    if not usable:
        return default

    def key(v):
        return tuple(int(p) for p in v.split("."))

    return max(usable, key=key)


def detect_runtime_version(repo_path, lang):
    """Return the major[.minor] version the repo actually runs, or the
    tool default. Hints: declared Dockerfile tags, .python-version /
    runtime.txt (python), package.json engines (node), python_requires."""
    if lang == "py":
        hints = [_tag_version_for("python", _dockerfile_from_tags(repo_path)),
                 _py_version_files(repo_path), _py_requires(repo_path)]
        return _pick_version(hints, _DEFAULT_PY)
    hints = [_tag_version_for("node", _dockerfile_from_tags(repo_path)),
             _node_engines(repo_path)]
    return _pick_version(hints, _DEFAULT_NODE)


def _tag_version_for(lang, tag_pairs):
    for t_lang, tag in tag_pairs:
        if t_lang != lang or not tag:
            continue
        if lang == "python":
            m = _TAG_PLAIN_VERSION_RE.match(tag)
            if m:
                return m.group(1) if not m.group(2) \
                    else f"{m.group(1)}.{m.group(2)}"
            m = _TAG_PY_VERSION_RE.match(tag)
            if m:  # alpine3.8 / slim-buster3.7 style year tags
                return f"3.{m.group(2)}" if m.group(1) == "3" else None
        else:
            m = _TAG_PLAIN_VERSION_RE.match(tag)
            if m:
                return m.group(1) if not m.group(2) else f"{m.group(1)}.{m.group(2)}"
    return None


def _first_declared_dockerfile(repo_path):
    """Name of the repo's own declared runtime Dockerfile (priority order),
    for explicit build-failure escalation — or None."""
    preferred = ["Dockerfile", "Dockerfile.app", "Dockerfile.web",
                 "Dockerfile.prod", "Dockerfile.api", "Dockerfile.server"]
    files = []
    for root, dirs, names in os.walk(repo_path):
        dirs[:] = [d for d in dirs if d not in _SKIP]
        for fname in names:
            if fname == "Dockerfile" or fname.startswith("Dockerfile."):
                path = os.path.join(root, fname)
                try:
                    if not stat.S_ISREG(os.lstat(path).st_mode):
                        continue
                except OSError:
                    continue
                with open(path, encoding="utf-8", errors="replace") as fh:
                    if fh.readline().startswith("# Generated by PatchProof"):
                        continue  # our own earlier artifact
                files.append(os.path.relpath(path, repo_path))
    files.sort(key=lambda f: (preferred.index(os.path.basename(f))
                              if os.path.basename(f) in preferred else 99, f))
    return files[0] if files else None


def _detect_manifest(repo_path):
    found = deps.scan_repo(repo_path)
    for kind in ("requirements", "pyproject.toml", "package.json"):
        entry = next((e for entries in found.values() for e in entries
                      if e["manifest"] == kind), None)
        if entry:
            return kind, entry["path"]
    return None, None


def _copy(src, dst=None):
    """Dockerfile JSON-array COPY — safe for paths with spaces/metachars."""
    dst = dst or src
    return "COPY " + json.dumps([src, dst])


def _install_block(manifest_name, manifest_rel, ctx_root):
    if manifest_name == "requirements":
        return [_copy(manifest_rel),
                f"RUN pip install --no-cache-dir -r {shlex.quote(manifest_rel)}"]
    if manifest_name == "package.json":
        manifest_dir = os.path.dirname(manifest_rel)
        lockfiles = [f for f in ("package-lock.json", "npm-shrinkwrap.json",
                                 "yarn.lock", "pnpm-lock.yaml")
                     if os.path.isfile(os.path.join(ctx_root, manifest_dir, f))]
        lines = [_copy(manifest_rel)]
        lines += [_copy(os.path.join(manifest_dir, f) if manifest_dir else f)
                  for f in lockfiles]
        install = "npm ci --omit=dev" if lockfiles else "npm install --omit=dev"
        # Manifest scanning is recursive: the Node project root is the
        # manifest's directory, not necessarily the context root.
        lines.append(f"RUN cd {shlex.quote(manifest_dir)} && {install}" if manifest_dir
                     else f"RUN {install}")
        return lines
    if manifest_name == "pyproject.toml":
        # A pyproject manifest alone is not installable: source first.
        return None
    return None


_COPY_IGNORE = (".git", "venv", ".venv", "__pycache__", "node_modules",
                "data", "output")

# Evidence the entry starts its own server loop (safe to exec directly) —
# Python and Node alike.
_PY_SELF_SERVING_RE = re.compile(
    r"uvicorn\.run\(|run_app\(|app\.run\(|serve_forever\(|create_server\(|"
    r"make_server\(")
_PY_LISTEN_RE = re.compile(r"\.listen\(")
_PY_LISTEN_LOCAL_RE = re.compile(
    r"\.listen\(\s*(?:\d+|['\"][\w.]+['\"])\s*,\s*['\"]"
    r"(?:127\.0\.0\.1|localhost|::1)['\"]")
_PY_LOOP_RE = re.compile(r"serve_forever\(|IOLoop|run_forever\(|\.start\(")
_NODE_LISTEN_RE = re.compile(
    r"\.listen\(\s*(?:\d+|['\"][\w.]+['\"])\s*,\s*['\"]"
    r"(?:127\.0\.0\.1|localhost|::1)['\"]")
# Evidence the entry exposes an ASGI/WSGI application object (needs a server
# launcher — `python entry.py` would define the app and exit).
_APP_OBJECT_RE = re.compile(
    r"^\s*(\w+)\s*=\s*("
    r"FastAPI|Flask|Starlette|Quart|Sanic|Bottle|"
    r"web\.Application|aiohttp\.web\.Application)\(", re.M)


def _derive_start_command(entry, repo_path):
    """Return a runtime command that actually SERVES the app, or raise.

    A bare `[python, entry]` only works when the entry starts its own server
    loop; an entry that merely defines an ASGI/WSGI app object exits without
    serving, so it gets a uvicorn command; anything else is a hard failure
    rather than a start command we cannot prove works. Node entries must show
    a listener/server loop too — console-only scripts exit immediately.
    """
    runner = "python" if entry.endswith(".py") else "node"
    try:
        with open(os.path.join(repo_path, entry), encoding="utf-8",
                  errors="replace") as fh:
            text = fh.read()
    except OSError:
        text = ""
    if runner == "python":
        if _PY_LISTEN_RE.search(text):
            # A .listen() must bind loopback explicitly (tornado-style
            # binds default to all interfaces); runners like uvicorn.run/
            # run_app/serve_forever default to 127.0.0.1 safely.
            self_serving = (_PY_LISTEN_LOCAL_RE.search(text)
                            and _PY_LOOP_RE.search(text))
        else:
            self_serving = _PY_SELF_SERVING_RE.search(text)
    else:
        self_serving = _NODE_LISTEN_RE.search(text)
    if not self_serving:
        if runner == "python" and _PY_LISTEN_RE.search(text) and \
                not _PY_LISTEN_LOCAL_RE.search(text):
            raise ValueError(
                f"cannot prove a safe serving command for {entry}: a "
                f".listen() call exists but does not bind 127.0.0.1/"
                f"localhost — sandbox services must bind loopback only; "
                f"fix the bind or supply the startup command explicitly")
        if runner == "node":
            if ".listen(" in text:
                raise ValueError(
                    f"cannot prove a safe serving command for {entry}: a "
                    f".listen() call exists but does not bind 127.0.0.1/"
                    f"localhost — sandbox services must bind loopback only; "
                    f"fix the bind or supply the startup command explicitly")
            raise ValueError(
                f"cannot prove a serving command for {entry}: the script "
                f"shows no localhost-bound listener (listen(3000, "
                f"'127.0.0.1')); supply the startup command explicitly")
        m = _APP_OBJECT_RE.search(text)
        if m:
            module = entry[:-3].replace(os.sep, ".").replace("/", ".")
            module = re.sub(r"\.__init__$", "", module)
            return ["uvicorn", f"{module}:{m.group(1)}",
                    "--host", "127.0.0.1", "--port", "8000"]
        raise ValueError(
            f"cannot prove a serving command for {entry}: it neither starts a "
            f"server loop nor exposes a recognized ASGI/WSGI app object; supply "
            f"the startup command explicitly instead of a start that exits")
    return [runner, entry]


def generate(repo_path, out_dir=None, force=False):
    """Write a minimal, version-matched `Dockerfile.patchproof` into the
    build context. The repo's own Dockerfile* files are never overwritten
    and never executed."""
    repo_path = os.path.abspath(repo_path)
    out_dir = os.path.abspath(out_dir) if out_dir else repo_path

    if out_dir != repo_path:
        if os.path.exists(out_dir) and os.listdir(out_dir):
            raise FileExistsError(f"{out_dir} is not empty; refusing to mix contexts")
        shutil.copytree(repo_path, out_dir,
                        ignore=shutil.ignore_patterns(*_COPY_IGNORE),
                        dirs_exist_ok=True)

    entry = _find_entry(repo_path)
    if not entry:
        raise ValueError(
            f"no runnable application entry detected in {repo_path} "
            f"(looked for {', '.join(_ENTRY_CANDIDATES)}); supply the entry "
            f"explicitly instead of generating a Dockerfile that cannot start")
    manifest_name, manifest_path = _detect_manifest(repo_path)
    is_py = entry.endswith(".py")
    runner = "python" if is_py else "node"
    start_command = _derive_start_command(entry, repo_path)
    version = detect_runtime_version(repo_path, "py" if is_py else "js")
    base = (f"python:{version}-slim" if is_py else f"node:{version}-slim")

    lines = [_GENERATED_MARKER, f"FROM {base}", "WORKDIR /srv"]
    # Compiled dependencies (psycopg2, cffi, ...) need tooling the slim
    # base lacks — install a uniform, per-language build-tools layer BEFORE
    # the repo deps. Repo deps that pin their own versions re-assert during
    # the install, so the vulnerable environment stays intact.
    if manifest_path and is_py:
        lines.append(
            "RUN apt-get update && apt-get install -y --no-install-recommends "
            "gcc python3-dev libpq-dev libffi-dev "
            "&& rm -rf /var/lib/apt/lists/*")
    if start_command[0] == "uvicorn":
        # App-object derivation emits a uvicorn launch, but the repo's own
        # requirements may not include it. Install BEFORE the repo deps so
        # a pinned uvicorn (uvicorn==0.29.0) re-asserts itself during
        # `pip install -r requirements.txt` and the vulnerable environment
        # stays intact.
        lines.append('RUN pip install --no-cache-dir "uvicorn>=0.30"')
    if manifest_path and manifest_name == "pyproject.toml":
        lines += ["COPY . /srv", "RUN pip install --no-cache-dir ."]
    else:
        install_lines = (_install_block(manifest_name, manifest_path,
                                        out_dir) if manifest_path else [])
        lines += install_lines + ["COPY . /srv"]
    lines.append(f"CMD {json.dumps(start_command)}")

    _write_file(os.path.join(out_dir, "Dockerfile.patchproof"),
                "\n".join(lines) + "\n", force)
    _write_file(os.path.join(out_dir, ".dockerignore"),
                "\n".join((".git", ".env", ".env.*", "*.pem", "*.key", "*.p12",
                           "*.pfx", "id_rsa*", ".aws", ".ssh", ".npmrc",
                           ".pypirc", "credentials*", "*.credentials",
                           "venv", ".venv", "__pycache__", "node_modules",
                           "data", "output")) + "\n", force)

    # The sandbox start command overrides the Dockerfile CMD, so persist the
    # validated startup command for the reproducer to consume (it cannot
    # assume `uvicorn main:app` for arbitrary repos).
    # Two-tier build (ADR-017): the synthesized minimal definition is the
    # primary; if its install fails (legacy compiled deps), the reproducer
    # escalates to the repo's OWN declared Dockerfile via the -f argument —
    # an explicit, documented escalation of the build-time trust boundary.
    fallback = _first_declared_dockerfile(repo_path)
    context_record = {
        "dockerfile": os.path.join(out_dir, "Dockerfile.patchproof"),
        "dockerfile_name": "Dockerfile.patchproof",
        "fallback_dockerfile": fallback,
        "base_image": base,
        "runtime_version": version,
        "entry": entry,
        "start_command": start_command,
        "dependency_manifest": manifest_path,
        "build_context": out_dir,
        "source": "synthesized",
        "generated": True,
    }
    _write_file(os.path.join(out_dir, "patchproof-build-context.json"),
                json.dumps(context_record, indent=2, ensure_ascii=False) + "\n",
                force)

    return context_record


def main(argv=None):
    parser = argparse.ArgumentParser(description="PatchProof build-context generator")
    parser.add_argument("repo_path", help="path to the target repository")
    parser.add_argument("--out", help="write a complete build context here (default: repo path)")
    parser.add_argument("--force", action="store_true",
                        help="replace an existing generated Dockerfile.patchproof/.dockerignore")
    args = parser.parse_args(argv)

    result = generate(args.repo_path, args.out, args.force)
    print(json.dumps(result, indent=2, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    sys.exit(main())
