"""Unit tests for gen_context — the Dockerfile.patchproof contract.

The working build definition is ALWAYS `Dockerfile.patchproof` (built via
sandbox_build's -f support): a repo's own Dockerfile* files are never
overwritten. Sources: verbatim reuse of an allowlisted declared definition
(with its WORKDIR honored), or synthesis of the generic default.
"""

import json
import os

import pytest

from agent.analyzer import gen_context, deps

_SELF_SERVING_APP = (
    "import uvicorn\n"
    "app = 'placeholder'\n"
    "if __name__ == '__main__':\n"
    "    uvicorn.run(app)\n")
_NODE_LISTENER = ("const http = require('http');\n"
                  "http.createServer(() => {}).listen(3000, '127.0.0.1');\n")


def _write(path, content):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(content)


def _require(repo, body="pyyaml==3.13\n"):
    _write(os.path.join(repo, "requirements.txt"), body)


def _pf(repo):
    return os.path.join(str(repo), "Dockerfile.patchproof")


# ------------------------------------------------------------- synthesis

def test_synthesizes_generic_default(tmp_path):
    repo = tmp_path / "app"
    _require(repo)
    _write(os.path.join(repo, "main.py"), _SELF_SERVING_APP)
    result = gen_context.generate(str(repo), str(repo))
    assert result["source"] == "synthesized"
    assert result["base_image"] == "python:3.11-slim"
    assert result["dockerfile_name"] == "Dockerfile.patchproof"
    dockerfile = open(_pf(repo), encoding="utf-8").read()
    assert dockerfile.startswith("# Generated by PatchProof")
    assert "FROM python:3.11-slim" in dockerfile
    assert 'CMD ["python", "main.py"]' in dockerfile
    # the repo's own files are never written
    assert not os.path.exists(os.path.join(str(repo), "Dockerfile"))


def test_refuses_overwrite_of_its_own_output(tmp_path):
    repo = tmp_path / "app"
    _require(repo)
    _write(os.path.join(repo, "main.py"), _SELF_SERVING_APP)
    gen_context.generate(str(repo), str(repo))
    with pytest.raises(FileExistsError):
        gen_context.generate(str(repo), str(repo))
    gen_context.generate(str(repo), str(repo), force=True)


def test_out_is_complete_context(tmp_path):
    repo = tmp_path / "app"
    _require(repo)
    _write(os.path.join(repo, "main.py"), _SELF_SERVING_APP)
    out = tmp_path / "ctx"
    result = gen_context.generate(str(repo), str(out))
    assert result["build_context"] == os.path.abspath(str(out))
    for name in ("Dockerfile.patchproof", "main.py", "requirements.txt"):
        assert os.path.isfile(out / name)


def test_dockerignore_blocks_secrets(tmp_path):
    repo = tmp_path / "app"
    _require(repo)
    _write(os.path.join(repo, "main.py"), _SELF_SERVING_APP)
    gen_context.generate(str(repo), str(repo))
    di = open(os.path.join(str(repo), ".dockerignore"), encoding="utf-8").read()
    for pattern in (".env", "*.pem", "id_rsa*", ".aws", ".ssh"):
        assert pattern in di


def test_installs_uvicorn_launcher_for_app_object(tmp_path):
    repo = tmp_path / "app"
    _require(repo, body="fastapi==0.115.0\n")  # no uvicorn declared
    _write(os.path.join(repo, "main.py"),
           "from fastapi import FastAPI\napp = FastAPI()\n")
    result = gen_context.generate(str(repo), str(repo))
    assert result["start_command"][0] == "uvicorn"
    dockerfile = open(_pf(repo), encoding="utf-8").read()
    assert "pip install" in dockerfile and "uvicorn" in dockerfile
    # launcher installs BEFORE repo deps so a repo pin re-asserts itself
    assert dockerfile.index("uvicorn>=0.30") < dockerfile.index("-r requirements.txt")


def test_node_synthesis_uses_npm_and_lockfile(tmp_path):
    repo = tmp_path / "app"
    _write(os.path.join(repo, "package.json"),
           json.dumps({"dependencies": {"yaml": "1.10.0"}}))
    _write(os.path.join(repo, "package-lock.json"), "{}")
    _write(os.path.join(repo, "server.js"), _NODE_LISTENER)
    result = gen_context.generate(str(repo), str(repo))
    assert result["base_image"] == "node:20-slim"
    dockerfile = open(_pf(repo), encoding="utf-8").read()
    assert 'CMD ["node", "server.js"]' in dockerfile
    assert "npm ci" in dockerfile and "package-lock.json" in dockerfile


def test_nested_npm_project_installs_at_its_root(tmp_path):
    repo = tmp_path / "app"
    _write(os.path.join(repo, "frontend", "package.json"), json.dumps(
        {"dependencies": {"yaml": "1.10.0"}}))
    _write(os.path.join(repo, "frontend", "package-lock.json"), "{}")
    _write(os.path.join(repo, "frontend", "server.js"), _NODE_LISTENER)
    result = gen_context.generate(str(repo), str(repo))
    dockerfile = open(_pf(repo), encoding="utf-8").read()
    assert 'COPY ["frontend/package.json", "frontend/package.json"]' in dockerfile
    assert "RUN cd frontend && npm ci" in dockerfile
    assert 'CMD ["node", "frontend/server.js"]' in dockerfile


def test_quoting_survives_spaces_and_json_metachars(tmp_path):
    repo = tmp_path / "app"
    _write(os.path.join(repo, "front end", "package.json"), json.dumps(
        {"dependencies": {"yaml": "1.10.0"}}))
    _write(os.path.join(repo, "front end", "server.js"), _NODE_LISTENER)
    gen_context.generate(str(repo), str(repo))
    dockerfile = open(_pf(repo), encoding="utf-8").read()
    assert 'COPY ["front end/package.json", "front end/package.json"]' in dockerfile
    assert "RUN cd 'front end' && npm install" in dockerfile
    cmd_line = next(l for l in dockerfile.splitlines() if l.startswith("CMD "))
    assert json.loads(cmd_line[4:])[1] == "front end/server.js"


def test_fails_without_entry(tmp_path):
    repo = tmp_path / "app"
    _require(repo)
    _write(os.path.join(repo, "lib.py"), "print('library only')\n")
    with pytest.raises(ValueError):
        gen_context.generate(str(repo), str(repo))


def test_fails_without_serving_command(tmp_path):
    repo = tmp_path / "app"
    _require(repo)
    _write(os.path.join(repo, "main.py"), "print('library only')\n")
    with pytest.raises(ValueError):
        gen_context.generate(str(repo), str(repo))


def test_node_constructor_without_listen_rejected(tmp_path):
    repo = tmp_path / "app"
    _write(os.path.join(repo, "package.json"), json.dumps(
        {"dependencies": {"express": "4.19.0"}}))
    _write(os.path.join(repo, "server.js"),
           "const http = require('http');\nhttp.createServer(() => {});\n")
    with pytest.raises(ValueError):
        gen_context.generate(str(repo), str(repo))


def test_all_interface_binds_rejected(tmp_path):
    for lang, entry, body in (
            ("node", "server.js", "http.createServer(()=>{}).listen(3000);\n"),
            ("py", "main.py",
             "import tornado.ioloop\nimport tornado.web\n"
             "app = tornado.web.Application([])\napp.listen(8888)\n"
             "tornado.ioloop.IOLoop.current().start()\n")):
        repo = tmp_path / f"app-{lang}"
        if lang == "node":
            _write(os.path.join(repo, "package.json"), json.dumps(
                {"dependencies": {}}))
            _write(os.path.join(repo, entry), body)
        else:
            _require(repo)
            _write(os.path.join(repo, entry), body)
        with pytest.raises(ValueError):
            gen_context.generate(str(repo), str(repo))


def test_python_listener_loop_accepted(tmp_path):
    repo = tmp_path / "app"
    _require(repo)
    _write(os.path.join(repo, "main.py"), (
        "import tornado.ioloop\nimport tornado.web\n"
        "app = tornado.web.Application([])\n"
        "app.listen(8888, '127.0.0.1')\n"
        "tornado.ioloop.IOLoop.current().start()\n"))
    result = gen_context.generate(str(repo), str(repo))
    assert result["start_command"] == ["python", "main.py"]


# ------------------------------------------------------- declared reuse

def test_reuses_declared_dockerfile_verbatim(tmp_path):
    repo = tmp_path / "app"
    _require(repo, body="old-pin==1.0\n")
    _write(os.path.join(repo, "Dockerfile.app"),
           "FROM python:alpine3.8\nRUN apk add --no-cache gcc musl-dev\n")
    _write(os.path.join(repo, "main.py"), _SELF_SERVING_APP)
    result = gen_context.generate(str(repo), str(repo))
    assert result["source"] == "repo-dockerfile"
    assert result["base_image"] == "python:alpine3.8"
    assert result["generated"] is True  # the .patchproof build file is generated
    # verbatim: the repo's own RUN steps (build tooling) survive
    dockerfile = open(_pf(repo), encoding="utf-8").read()
    assert "apk add --no-cache gcc musl-dev" in dockerfile
    # the repo's own Dockerfile* files are untouched
    assert open(os.path.join(str(repo), "Dockerfile.app")).read() == \
        "FROM python:alpine3.8\nRUN apk add --no-cache gcc musl-dev\n"
    assert not os.path.exists(os.path.join(str(repo), "Dockerfile"))


def test_workdir_honored_in_start_command(tmp_path):
    repo = tmp_path / "app"
    _require(repo)
    _write(os.path.join(repo, "Dockerfile.app"), (
        "FROM python:3.9-slim\nWORKDIR /app\n"
        "COPY . /app\nRUN pip install -r requirements.txt\n"))
    _write(os.path.join(repo, "main.py"), _SELF_SERVING_APP)
    result = gen_context.generate(str(repo), str(repo))
    assert result["workdir"] == "/app"
    dockerfile = open(_pf(repo), encoding="utf-8").read()
    cmd_line = next(l for l in dockerfile.splitlines() if l.startswith("CMD "))
    assert json.loads(cmd_line[4:]) == ["sh", "-c",
                                        "cd /app && python main.py"]


def test_unusable_base_falls_back_to_generic(tmp_path):
    repo = tmp_path / "app"
    _require(repo)
    _write(os.path.join(repo, "Dockerfile"), "FROM mysql:8.0\n")
    _write(os.path.join(repo, "main.py"), _SELF_SERVING_APP)
    result = gen_context.generate(str(repo), str(repo))
    # fallback to the generic default; the repo's own Dockerfile untouched
    assert result["source"] == "synthesized"
    assert result["base_image"] == "python:3.11-slim"
    assert open(os.path.join(str(repo), "Dockerfile")).read() == "FROM mysql:8.0\n"


def test_parametrized_from_falls_back(tmp_path):
    repo = tmp_path / "app"
    _require(repo)
    _write(os.path.join(repo, "Dockerfile"),
           "ARG BASE=python:3.8\nFROM ${BASE}\n")
    _write(os.path.join(repo, "main.py"), _SELF_SERVING_APP)
    result = gen_context.generate(str(repo), str(repo))
    assert result["source"] == "synthesized"
    assert open(os.path.join(str(repo), "Dockerfile")).read() == \
        "ARG BASE=python:3.8\nFROM ${BASE}\n"


def test_prefers_runtime_dockerfile_over_db(tmp_path):
    repo = tmp_path / "app"
    _require(repo)
    _write(os.path.join(repo, "Dockerfile.db"), "FROM mysql:8.0\n")
    _write(os.path.join(repo, "Dockerfile.app"), "FROM python:3.9-slim\n")
    _write(os.path.join(repo, "main.py"), _SELF_SERVING_APP)
    result = gen_context.generate(str(repo), str(repo))
    assert result["base_image"] == "python:3.9-slim"


def test_case_insensitive_from(tmp_path):
    repo = tmp_path / "app"
    _require(repo)
    _write(os.path.join(repo, "Dockerfile.app"),
           "  from python:3.8-slim AS build\n")
    _write(os.path.join(repo, "main.py"), _SELF_SERVING_APP)
    result = gen_context.generate(str(repo), str(repo))
    assert result["base_image"] == "python:3.8-slim"


def test_skips_its_own_generated_dockerfile(tmp_path):
    repo = tmp_path / "app"
    _require(repo)
    _write(os.path.join(repo, "Dockerfile"),
           "# Generated by PatchProof gen_context (safe to delete).\n"
           "FROM python:3.11-slim\n")  # stale artifact from an earlier run
    _write(os.path.join(repo, "Dockerfile.app"), "FROM python:alpine3.8\n")
    _write(os.path.join(repo, "main.py"), _SELF_SERVING_APP)
    result = gen_context.generate(str(repo), str(repo), force=True)
    assert result["base_image"] == "python:alpine3.8"


def test_symlinked_dockerfiles_skipped(tmp_path):
    repo = tmp_path / "app"
    _require(repo)
    _write(os.path.join(repo, "main.py"), _SELF_SERVING_APP)
    os.symlink("/dev/zero", os.path.join(repo, "Dockerfile.zero"))
    os.symlink("/etc/passwd", os.path.join(repo, "Dockerfile.esc"))
    result = gen_context.generate(str(repo), str(repo), force=True)
    assert result["source"] == "synthesized"  # fallback, no hang/leak


def test_from_flags_and_digests_handled(tmp_path):
    repo = tmp_path / "app"
    _require(repo)
    _write(os.path.join(repo, "Dockerfile.app"),
           "FROM --platform=linux/amd64 python:3.9-slim@sha256:" + "a" * 64 + "\n")
    _write(os.path.join(repo, "main.py"), _SELF_SERVING_APP)
    result = gen_context.generate(str(repo), str(repo), force=True)
    assert result["base_image"] == "python:3.9-slim@sha256:" + "a" * 64


def test_parser_directives_hoisted_above_marker(tmp_path):
    repo = tmp_path / "app"
    _require(repo)
    _write(os.path.join(repo, "Dockerfile.app"),
           "# syntax=docker/dockerfile:1\nFROM python:3.9-slim\n"
           "RUN --mount=type=cache target=/root/.cache pip install -r requirements.txt\n")
    _write(os.path.join(repo, "main.py"), _SELF_SERVING_APP)
    gen_context.generate(str(repo), str(repo), force=True)
    dockerfile = open(_pf(repo), encoding="utf-8").read()
    # the directive must precede our marker to stay recognized by Docker
    assert dockerfile.index("# syntax=docker/dockerfile:1") < \
        dockerfile.index("# Generated by PatchProof")
    assert "--mount=type=cache" in dockerfile


def test_inherited_entrypoint_cleared(tmp_path):
    repo = tmp_path / "app"
    _require(repo)
    _write(os.path.join(repo, "Dockerfile.app"), (
        "FROM python:3.9-slim\nENTRYPOINT [\"python\", \"-m\", \"server\"]\n"))
    _write(os.path.join(repo, "main.py"), _SELF_SERVING_APP)
    gen_context.generate(str(repo), str(repo), force=True)
    dockerfile = open(_pf(repo), encoding="utf-8").read()
    assert "ENTRYPOINT []" in dockerfile
    cmd = next(l for l in dockerfile.splitlines() if l.startswith("CMD "))
    assert json.loads(cmd[4:]) == ["python", "main.py"]


def test_workdir_scoped_to_final_stage_and_relative_resolution(tmp_path):
    repo = tmp_path / "app"
    _require(repo)
    _write(os.path.join(repo, "Dockerfile.app"), (
        "FROM python:3.9-slim AS build\nWORKDIR /build\n"
        "FROM python:3.9-slim\nWORKDIR build-out\nWORKDIR sub\n"))
    _write(os.path.join(repo, "main.py"), _SELF_SERVING_APP)
    result = gen_context.generate(str(repo), str(repo), force=True)
    # only the FINAL stage's workdir chain applies, relative steps resolve
    assert result["workdir"] == "/srv/build-out/sub"
    dockerfile = open(_pf(repo), encoding="utf-8").read()
    cmd = next(l for l in dockerfile.splitlines() if l.startswith("CMD "))
    assert json.loads(cmd[4:]) == ["sh", "-c",
                                   "cd /srv/build-out/sub && python main.py"]
