"""Unit tests for gen_context — version-matched minimal synthesis contract.

The working build definition is ALWAYS `Dockerfile.patchproof`: a minimal
official base matched to the repo's runtime version + our own uniform
install lines. Repo Dockerfile* files are read for version hints only and
are never overwritten or executed.
"""

import json
import os

import pytest

from agent.analyzer import gen_context

_SELF_SERVING_APP = (
    "import uvicorn\n"
    "app = 'placeholder'\n"
    "if __name__ == '__main__':\n"
    "    uvicorn.run(app)\n")
_NODE_LISTENER = ("const http = require('http');\n"
                  "http.createServer(() => {}).listen(3000, '127.0.0.1');\n")


def _write(path, content):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(content)


def _require(repo, body="pyyaml==3.13\n"):
    _write(os.path.join(repo, "requirements.txt"), body)


def _pf(repo):
    return os.path.join(str(repo), "Dockerfile.patchproof")


# ------------------------------------------------------------- synthesis

def test_synthesizes_version_matched_slim_base(tmp_path):
    repo = tmp_path / "app"
    _require(repo)
    _write(os.path.join(repo, "main.py"), _SELF_SERVING_APP)
    result = gen_context.generate(str(repo), str(repo))
    assert result["source"] == "synthesized"
    assert result["base_image"] == "python:3.11-slim"  # no hints → default
    assert result["runtime_version"] == "3.11"
    assert result["dockerfile_name"] == "Dockerfile.patchproof"
    dockerfile = open(_pf(repo), encoding="utf-8").read()
    assert dockerfile.startswith("# Generated by PatchProof")
    assert "FROM python:3.11-slim" in dockerfile
    assert 'CMD ["python", "main.py"]' in dockerfile
    # the repo's own Dockerfile* files are never created or written
    assert not os.path.exists(os.path.join(str(repo), "Dockerfile"))


def test_version_from_declared_dockerfile_tag(tmp_path):
    repo = tmp_path / "app"
    _require(repo)
    _write(os.path.join(repo, "Dockerfile.app"), "FROM python:alpine3.8\n")
    _write(os.path.join(repo, "main.py"), _SELF_SERVING_APP)
    result = gen_context.generate(str(repo), str(repo))
    assert result["runtime_version"] == "3.8"
    assert result["base_image"] == "python:3.8-slim"


def test_version_from_python_version_file(tmp_path):
    repo = tmp_path / "app"
    _require(repo)
    _write(os.path.join(repo, ".python-version"), "3.10.4\n")
    _write(os.path.join(repo, "main.py"), _SELF_SERVING_APP)
    result = gen_context.generate(str(repo), str(repo))
    assert result["runtime_version"] == "3.10"


def test_version_from_python_requires(tmp_path):
    repo = tmp_path / "app"
    _require(repo)
    _write(os.path.join(repo, "setup.py"),
           "python_requires='>=3.9'\n")
    _write(os.path.join(repo, "main.py"), _SELF_SERVING_APP)
    result = gen_context.generate(str(repo), str(repo))
    assert result["runtime_version"] == "3.9"


def test_node_version_from_engines(tmp_path):
    repo = tmp_path / "app"
    _write(os.path.join(repo, "package.json"), json.dumps(
        {"engines": {"node": ">=18"}, "dependencies": {}}))
    _write(os.path.join(repo, "server.js"), _NODE_LISTENER)
    result = gen_context.generate(str(repo), str(repo))
    assert result["base_image"] == "node:18-slim"


def test_node_version_from_declared_dockerfile_tag(tmp_path):
    repo = tmp_path / "app"
    _write(os.path.join(repo, "Dockerfile.prod"), "FROM node:20-bookworm\n")
    _write(os.path.join(repo, "server.js"), _NODE_LISTENER)
    result = gen_context.generate(str(repo), str(repo))
    assert result["base_image"] == "node:20-slim"


# --------------------------------------------------- repo files untouched

def test_repo_dockerfile_never_overwritten(tmp_path):
    repo = tmp_path / "app"
    _require(repo)
    _write(os.path.join(repo, "Dockerfile.app"), "FROM python:alpine3.8\n")
    _write(os.path.join(repo, "main.py"), _SELF_SERVING_APP)
    gen_context.generate(str(repo), str(repo), force=True)
    assert open(os.path.join(str(repo), "Dockerfile.app")).read() == \
        "FROM python:alpine3.8\n"
    # only our patchproof artifact + hardening files are added
    added = {f for f in os.listdir(str(repo))
             if f in ("Dockerfile.patchproof", ".dockerignore",
                      "patchproof-build-context.json")}
    assert added == {"Dockerfile.patchproof", ".dockerignore",
                     "patchproof-build-context.json"}


def test_refuses_overwrite_of_its_own_output(tmp_path):
    repo = tmp_path / "app"
    _require(repo)
    _write(os.path.join(repo, "main.py"), _SELF_SERVING_APP)
    gen_context.generate(str(repo), str(repo))
    with pytest.raises(FileExistsError):
        gen_context.generate(str(repo), str(repo))
    gen_context.generate(str(repo), str(repo), force=True)


def test_refuses_symlink_at_output_name(tmp_path):
    repo = tmp_path / "app"
    _require(repo)
    _write(os.path.join(repo, "main.py"), _SELF_SERVING_APP)
    os.symlink("/etc/passwd", _pf(repo))
    with pytest.raises(RuntimeError):
        gen_context.generate(str(repo), str(repo), force=True)
    # target untouched
    assert open("/etc/passwd", encoding="utf-8", errors="ignore").read()


def test_out_is_complete_context(tmp_path):
    repo = tmp_path / "app"
    _require(repo)
    _write(os.path.join(repo, "main.py"), _SELF_SERVING_APP)
    out = tmp_path / "ctx"
    result = gen_context.generate(str(repo), str(out))
    assert result["build_context"] == os.path.abspath(str(out))
    for name in ("Dockerfile.patchproof", "main.py", "requirements.txt"):
        assert os.path.isfile(out / name)


def test_dockerignore_blocks_secrets(tmp_path):
    repo = tmp_path / "app"
    _require(repo)
    _write(os.path.join(repo, "main.py"), _SELF_SERVING_APP)
    gen_context.generate(str(repo), str(repo))
    di = open(os.path.join(str(repo), ".dockerignore"), encoding="utf-8").read()
    for pattern in (".env", "*.pem", "id_rsa*", ".aws", ".ssh"):
        assert pattern in di


# ------------------------------------------------- start-command handling

def test_installs_uvicorn_launcher_before_repo_deps(tmp_path):
    repo = tmp_path / "app"
    _require(repo, body="fastapi==0.115.0\nuvicorn==0.29.0\n")
    _write(os.path.join(repo, "main.py"),
           "from fastapi import FastAPI\napp = FastAPI()\n")
    result = gen_context.generate(str(repo), str(repo))
    assert result["start_command"][0] == "uvicorn"
    dockerfile = open(_pf(repo), encoding="utf-8").read()
    # ordering: build tools -> uvicorn launcher -> repo deps, so a repo
    # pin (uvicorn==0.29.0) re-asserts itself during the deps install
    apt = dockerfile.index("apt-get install")
    uv = dockerfile.index("uvicorn>=0.30")
    deps_install = dockerfile.index("pip install --no-cache-dir -r requirements.txt")
    assert apt < uv < deps_install


def test_python_synth_includes_build_tools_before_deps(tmp_path):
    repo = tmp_path / "app"
    _require(repo)
    _write(os.path.join(repo, "main.py"), _SELF_SERVING_APP)
    gen_context.generate(str(repo), str(repo))
    dockerfile = open(_pf(repo), encoding="utf-8").read()
    assert "apt-get install" in dockerfile and "gcc" in dockerfile
    assert dockerfile.index("apt-get install") < dockerfile.index("-r")


def test_node_synth_has_no_apt_layer(tmp_path):
    repo = tmp_path / "app"
    _write(os.path.join(repo, "package.json"), json.dumps(
        {"dependencies": {}}))
    _write(os.path.join(repo, "server.js"), _NODE_LISTENER)
    gen_context.generate(str(repo), str(repo))
    dockerfile = open(_pf(repo), encoding="utf-8").read()
    assert "apt-get" not in dockerfile


def test_fallback_dockerfile_recorded_when_declared(tmp_path):
    repo = tmp_path / "app"
    _require(repo)
    _write(os.path.join(repo, "Dockerfile.app"),
           "FROM python:alpine3.8\nWORKDIR /app\n")
    _write(os.path.join(repo, "main.py"), _SELF_SERVING_APP)
    result = gen_context.generate(str(repo), str(repo))
    # synthesized stays primary; the repo's own definition is the
    # documented escalation when its install fails (with its workdir)
    assert result["source"] == "synthesized"
    assert result["fallback_dockerfile"] == "Dockerfile.app"
    assert result["fallback_workdir"] == "/app"


def test_no_fallback_when_no_declared_dockerfile(tmp_path):
    repo = tmp_path / "app"
    _require(repo)
    _write(os.path.join(repo, "main.py"), _SELF_SERVING_APP)
    result = gen_context.generate(str(repo), str(repo))
    assert result["fallback_dockerfile"] is None


def test_node_synthesis_uses_npm_and_lockfile(tmp_path):
    repo = tmp_path / "app"
    _write(os.path.join(repo, "package.json"),
           json.dumps({"dependencies": {"yaml": "1.10.0"}}))
    _write(os.path.join(repo, "package-lock.json"), "{}")
    _write(os.path.join(repo, "server.js"), _NODE_LISTENER)
    result = gen_context.generate(str(repo), str(repo))
    assert result["base_image"] == "node:20-slim"
    dockerfile = open(_pf(repo), encoding="utf-8").read()
    assert 'CMD ["node", "server.js"]' in dockerfile
    assert "npm ci" in dockerfile and "package-lock.json" in dockerfile


def test_nested_npm_project_installs_at_its_root(tmp_path):
    repo = tmp_path / "app"
    _write(os.path.join(repo, "frontend", "package.json"), json.dumps(
        {"dependencies": {"yaml": "1.10.0"}}))
    _write(os.path.join(repo, "frontend", "package-lock.json"), "{}")
    _write(os.path.join(repo, "frontend", "server.js"), _NODE_LISTENER)
    result = gen_context.generate(str(repo), str(repo))
    dockerfile = open(_pf(repo), encoding="utf-8").read()
    assert 'COPY ["frontend/package.json", "frontend/package.json"]' in dockerfile
    assert "RUN cd frontend && npm ci" in dockerfile
    assert 'CMD ["node", "frontend/server.js"]' in dockerfile


def test_quoting_survives_spaces_and_json_metachars(tmp_path):
    repo = tmp_path / "app"
    _write(os.path.join(repo, "front end", "package.json"), json.dumps(
        {"dependencies": {"yaml": "1.10.0"}}))
    _write(os.path.join(repo, "front end", "server.js"), _NODE_LISTENER)
    gen_context.generate(str(repo), str(repo))
    dockerfile = open(_pf(repo), encoding="utf-8").read()
    assert 'COPY ["front end/package.json", "front end/package.json"]' in dockerfile
    assert "RUN cd 'front end' && npm install" in dockerfile
    cmd_line = next(l for l in dockerfile.splitlines() if l.startswith("CMD "))
    assert json.loads(cmd_line[4:])[1] == "front end/server.js"


# --------------------------------------------------------- start failures

def test_fails_without_entry(tmp_path):
    repo = tmp_path / "app"
    _require(repo)
    _write(os.path.join(repo, "lib.py"), "print('library only')\n")
    with pytest.raises(ValueError):
        gen_context.generate(str(repo), str(repo))


def test_fails_without_serving_command(tmp_path):
    repo = tmp_path / "app"
    _require(repo)
    _write(os.path.join(repo, "main.py"), "print('library only')\n")
    with pytest.raises(ValueError):
        gen_context.generate(str(repo), str(repo))


def test_node_constructor_without_listen_rejected(tmp_path):
    repo = tmp_path / "app"
    _write(os.path.join(repo, "package.json"), json.dumps(
        {"dependencies": {"express": "4.19.0"}}))
    _write(os.path.join(repo, "server.js"),
           "const http = require('http');\nhttp.createServer(() => {});\n")
    with pytest.raises(ValueError):
        gen_context.generate(str(repo), str(repo))


def test_all_interface_binds_rejected(tmp_path):
    for lang, entry, body in (
            ("node", "server.js", "http.createServer(()=>{}).listen(3000);\n"),
            ("py", "main.py",
             "import tornado.ioloop\nimport tornado.web\n"
             "app = tornado.web.Application([])\napp.listen(8888)\n"
             "tornado.ioloop.IOLoop.current().start()\n")):
        repo = tmp_path / f"app-{lang}"
        if lang == "node":
            _write(os.path.join(repo, "package.json"), json.dumps(
                {"dependencies": {}}))
            _write(os.path.join(repo, entry), body)
        else:
            _require(repo)
            _write(os.path.join(repo, entry), body)
        with pytest.raises(ValueError):
            gen_context.generate(str(repo), str(repo))


def test_python_listener_loop_accepted(tmp_path):
    repo = tmp_path / "app"
    _require(repo)
    _write(os.path.join(repo, "main.py"), (
        "import tornado.ioloop\nimport tornado.web\n"
        "app = tornado.web.Application([])\n"
        "app.listen(8888, '127.0.0.1')\n"
        "tornado.ioloop.IOLoop.current().start()\n"))
    result = gen_context.generate(str(repo), str(repo))
    assert result["start_command"] == ["python", "main.py"]


def test_stale_generated_artifact_is_not_a_hint(tmp_path):
    repo = tmp_path / "app"
    _require(repo)
    _write(os.path.join(repo, ".python-version"), "3.8\n")
    _write(os.path.join(repo, "main.py"), _SELF_SERVING_APP)
    # stale artifact from a previous run (marker) — never a repo hint
    _write(os.path.join(repo, "Dockerfile.patchproof"),
           "# Generated by PatchProof gen_context (safe to delete).\n"
           "FROM python:3.12-slim\n")
    result = gen_context.generate(str(repo), str(repo), force=True)
    assert result["runtime_version"] == "3.8"


def test_first_concrete_hint_wins_no_max(tmp_path):
    repo = tmp_path / "app"
    _require(repo)
    _write(os.path.join(repo, "Dockerfile.app"), "FROM python:3.9-slim\n")
    _write(os.path.join(repo, ".python-version"), "3.8\n")
    _write(os.path.join(repo, "main.py"), _SELF_SERVING_APP)
    result = gen_context.generate(str(repo), str(repo))
    # declared Dockerfile tag takes precedence over the version-file floor
    assert result["runtime_version"] == "3.9"


def test_runtime_stage_tag_selected_not_builder(tmp_path):
    repo = tmp_path / "app"
    _require(repo)
    _write(os.path.join(repo, "Dockerfile.app"), (
        "FROM python:3.8-slim AS build\n"
        "FROM python:3.12-slim\nCOPY --from=build /w /w\n"))
    _write(os.path.join(repo, "main.py"), _SELF_SERVING_APP)
    result = gen_context.generate(str(repo), str(repo))
    # the LAST FROM is the runtime stage
    assert result["runtime_version"] == "3.12"


def test_registry_qualified_python_hint(tmp_path):
    repo = tmp_path / "app"
    _require(repo)
    _write(os.path.join(repo, "Dockerfile.app"),
           "FROM docker.io/library/python:3.12-slim\n")
    _write(os.path.join(repo, "main.py"), _SELF_SERVING_APP)
    result = gen_context.generate(str(repo), str(repo))
    assert result["runtime_version"] == "3.12"


def test_node_upper_bound_engine_ignored(tmp_path):
    repo = tmp_path / "app"
    _write(os.path.join(repo, "package.json"), json.dumps(
        {"engines": {"node": "<18"}}))
    _write(os.path.join(repo, "server.js"), _NODE_LISTENER)
    result = gen_context.generate(str(repo), str(repo))
    # "<18" names no usable runtime — the tool default applies
    assert result["base_image"] == "node:20-slim"


def test_node_caret_engine_selected(tmp_path):
    repo = tmp_path / "app"
    _write(os.path.join(repo, "package.json"), json.dumps(
        {"engines": {"node": "^20.1"}}))
    _write(os.path.join(repo, "server.js"), _NODE_LISTENER)
    result = gen_context.generate(str(repo), str(repo))
    assert result["base_image"] == "node:20-slim"


def test_workdir_in_context_record(tmp_path):
    repo = tmp_path / "app"
    _require(repo)
    _write(os.path.join(repo, "main.py"), _SELF_SERVING_APP)
    gen_context.generate(str(repo), str(repo))
    record = json.load(open(os.path.join(str(repo),
                       "patchproof-build-context.json"), encoding="utf-8"))
    assert record["workdir"] == "/srv"


def test_nested_python_requires_honored(tmp_path):
    repo = tmp_path / "app"
    _require(repo)
    _write(os.path.join(repo, "backend", "pyproject.toml"),
           '[project]\nname = "x"\nrequires-python = ">=3.12"\n')
    _write(os.path.join(repo, "backend", "main.py"), _SELF_SERVING_APP)
    _write(os.path.join(repo, "requirements.txt"), "old-pin==1.0\n")
    # detect the nested manifest as the app's manifest
    manifest = os.path.join(str(repo), "backend", "pyproject.toml")
    version = gen_context.detect_runtime_version(
        str(repo), "py", manifest_path=manifest)
    assert version == "3.12"


def test_python_strict_floor_and_exclusion_bumped_or_dropped(tmp_path):
    repo = tmp_path / "app"
    _require(repo)
    _write(os.path.join(repo, "setup.py"), "python_requires='>3.9'\n")
    _write(os.path.join(repo, "main.py"), _SELF_SERVING_APP)
    result = gen_context.generate(str(repo), str(repo))
    # >3.9 forbids 3.9 itself — the next minor satisfies it
    assert result["runtime_version"] == "3.10"

    repo2 = tmp_path / "app2"
    _require(repo2)
    _write(os.path.join(repo2, "pyproject.toml"),
           '[project]\nrequires-python = "!=3.11"\n')
    _write(os.path.join(repo2, "main.py"), _SELF_SERVING_APP)
    result2 = gen_context.generate(str(repo2), str(repo2))
    # != names no single satisfying runtime — fall back to the default
    assert result2["runtime_version"] == "3.11"


def test_python_upper_bound_satisfied(tmp_path):
    repo = tmp_path / "app"
    _require(repo)
    _write(os.path.join(repo, "setup.py"),
           "python_requires='<3.11'\n")
    _write(os.path.join(repo, "main.py"), _SELF_SERVING_APP)
    result = gen_context.generate(str(repo), str(repo))
    # default 3.11 would VIOLATE <3.11 — the highest satisfying version is 3.10
    assert result["runtime_version"] == "3.10"
    assert result["base_image"] == "python:3.10-slim"


def test_fallback_workdir_none_on_variable_workdir(tmp_path):
    repo = tmp_path / "app"
    _require(repo)
    _write(os.path.join(repo, "Dockerfile.app"),
           "FROM python:alpine3.8\nWORKDIR $APP_DIR\n")
    _write(os.path.join(repo, "main.py"), _SELF_SERVING_APP)
    result = gen_context.generate(str(repo), str(repo))
    assert result["fallback_workdir"] is None


def test_exact_maintenance_pin_yields_no_hint(tmp_path):
    repo = tmp_path / "app"
    _require(repo)
    _write(os.path.join(repo, "pyproject.toml"),
           '[project]\nrequires-python = "==3.10.5"\n')
    _write(os.path.join(repo, "main.py"), _SELF_SERVING_APP)
    result = gen_context.generate(str(repo), str(repo))
    # exact patch pin can't map to a major.minor image tag without violating
    # PEP440 exact matching -> no hint (fail open; pip enforces on install)
    assert result["runtime_version"] == "3.11"


def test_multiline_python_requires_honored(tmp_path):
    repo = tmp_path / "app"
    _require(repo)
    _write(os.path.join(repo, "setup.py"),
           "python_requires=(\n    \">=3.9,<3.12\"\n)\n")
    _write(os.path.join(repo, "main.py"), _SELF_SERVING_APP)
    result = gen_context.generate(str(repo), str(repo))
    assert result["runtime_version"] == "3.9"  # >=3.9,<3.12 -> floor 3.9


def test_fallback_rejected_when_base_not_allowlisted(tmp_path):
    repo = tmp_path / "app"
    _require(repo)
    _write(os.path.join(repo, "Dockerfile"),
           "FROM ubuntu:22.04\nWORKDIR /app\n")
    _write(os.path.join(repo, "main.py"), _SELF_SERVING_APP)
    result = gen_context.generate(str(repo), str(repo))
    # tier-2 escalation must keep the strict official python/node base
    # allowlist (ADR-016: repo content stays inert data) — a repo-controlled
    # foreign base is never offered as the fallback
    assert result["fallback_dockerfile"] is None


def test_fallback_rejected_when_runtime_base_not_allowlisted(tmp_path):
    repo = tmp_path / "app"
    _require(repo)
    _write(os.path.join(repo, "Dockerfile.app"),
           "FROM python:3.9-slim AS build\n"
           "RUN echo build\n"
           "FROM nginx:1.25\n"
           "WORKDIR /app\n")
    _write(os.path.join(repo, "main.py"), _SELF_SERVING_APP)
    result = gen_context.generate(str(repo), str(repo))
    # the LAST/runtime FROM is nginx (not allowlisted) -> no fallback
    assert result["fallback_dockerfile"] is None


def test_fallback_rejected_when_pseudo_official_foreign_base(tmp_path):
    repo = tmp_path / "app"
    _require(repo)
    # last segment is "python" but it's a foreign/org-qualified image
    _write(os.path.join(repo, "Dockerfile.app"),
           "FROM evilcorp/python:3.11\nWORKDIR /app\n")
    _write(os.path.join(repo, "main.py"), _SELF_SERVING_APP)
    result = gen_context.generate(str(repo), str(repo))
    assert result["fallback_dockerfile"] is None


def test_fallback_rejected_when_variable_runtime_base(tmp_path):
    repo = tmp_path / "app"
    _require(repo)
    # builder stage uses official python, but the runtime FROM is a variable
    # (unresolvable image) -> must NOT qualify
    _write(os.path.join(repo, "Dockerfile.app"),
           "FROM python:3.11-slim AS build\nRUN true\n"
           "FROM ${RUNTIME_BASE}\nWORKDIR /app\n")
    _write(os.path.join(repo, "main.py"), _SELF_SERVING_APP)
    result = gen_context.generate(str(repo), str(repo))
    assert result["fallback_dockerfile"] is None


def test_fallback_allows_official_library_registry_form(tmp_path):
    repo = tmp_path / "app"
    _require(repo)
    _write(os.path.join(repo, "Dockerfile.app"),
           "FROM docker.io/library/python:3.11-slim\nWORKDIR /app\n")
    _write(os.path.join(repo, "main.py"), _SELF_SERVING_APP)
    result = gen_context.generate(str(repo), str(repo))
    assert result["fallback_dockerfile"] == "Dockerfile.app"


def test_fallback_reads_full_file_for_final_from(tmp_path):
    repo = tmp_path / "app"
    _require(repo)
    # >20KB of comments BEFORE a foreign runtime FROM: old readlines(20000)
    # would truncate it; the final FROM must still be seen and rejected
    pad = "# " + ("x" * 22000) + "\n"
    _write(os.path.join(repo, "Dockerfile.app"),
           "FROM python:3.11-slim AS build\nRUN true\n" + pad +
           "FROM nginx:1.25\nWORKDIR /app\n")
    _write(os.path.join(repo, "main.py"), _SELF_SERVING_APP)
    result = gen_context.generate(str(repo), str(repo))
    assert result["fallback_dockerfile"] is None


def test_fallback_rejects_digest_base(tmp_path):
    repo = tmp_path / "app"
    _require(repo)
    _write(os.path.join(repo, "Dockerfile.app"),
           "FROM python@sha256:abc123\nWORKDIR /app\n")
    _write(os.path.join(repo, "main.py"), _SELF_SERVING_APP)
    result = gen_context.generate(str(repo), str(repo))
    assert result["fallback_dockerfile"] is None


def test_fallback_rejects_empty_tag_base(tmp_path):
    repo = tmp_path / "app"
    _require(repo)
    _write(os.path.join(repo, "Dockerfile.app"),
           "FROM python:\nWORKDIR /app\n")
    _write(os.path.join(repo, "main.py"), _SELF_SERVING_APP)
    result = gen_context.generate(str(repo), str(repo))
    assert result["fallback_dockerfile"] is None


def test_fallback_rejects_node_base_for_python_project(tmp_path):
    repo = tmp_path / "app"
    _require(repo)  # python project -> base language must be python
    _write(os.path.join(repo, "Dockerfile.app"),
           "FROM node:20-slim\nWORKDIR /app\n")
    _write(os.path.join(repo, "main.py"), _SELF_SERVING_APP)
    result = gen_context.generate(str(repo), str(repo))
    # a node base cannot run the recorded python startup command
    assert result["fallback_dockerfile"] is None


def test_fallback_allows_node_base_for_node_project(tmp_path):
    repo = tmp_path / "app"
    _write(os.path.join(repo, "package.json"),
           json.dumps({"dependencies": {"yaml": "1.10.0"}}))
    _write(os.path.join(repo, "server.js"), _NODE_LISTENER)
    _write(os.path.join(repo, "Dockerfile.app"),
           "FROM node:20-slim\nWORKDIR /app\n")
    result = gen_context.generate(str(repo), str(repo))
    assert result["fallback_dockerfile"] == "Dockerfile.app"


def test_fallback_rejects_malformed_tag_slash(tmp_path):
    repo = tmp_path / "app"
    _require(repo)
    _write(os.path.join(repo, "Dockerfile.app"),
           "FROM python:bad/tag\nWORKDIR /app\n")
    _write(os.path.join(repo, "main.py"), _SELF_SERVING_APP)
    result = gen_context.generate(str(repo), str(repo))
    assert result["fallback_dockerfile"] is None


def test_fallback_rejects_malformed_tag_bang(tmp_path):
    repo = tmp_path / "app"
    _require(repo)
    _write(os.path.join(repo, "Dockerfile.app"),
           "FROM python:bad!\nWORKDIR /app\n")
    _write(os.path.join(repo, "main.py"), _SELF_SERVING_APP)
    result = gen_context.generate(str(repo), str(repo))
    assert result["fallback_dockerfile"] is None


def test_fallback_rejects_leading_slash_reference(tmp_path):
    repo = tmp_path / "app"
    _require(repo)
    _write(os.path.join(repo, "Dockerfile.app"),
           "FROM /python:3.11-slim\nWORKDIR /app\n")
    _write(os.path.join(repo, "main.py"), _SELF_SERVING_APP)
    assert gen_context.generate(str(repo), str(repo))["fallback_dockerfile"] is None


def test_fallback_rejects_trailing_slash_reference(tmp_path):
    repo = tmp_path / "app"
    _require(repo)
    _write(os.path.join(repo, "Dockerfile.app"),
           "FROM python/:3.11-slim\nWORKDIR /app\n")
    _write(os.path.join(repo, "main.py"), _SELF_SERVING_APP)
    assert gen_context.generate(str(repo), str(repo))["fallback_dockerfile"] is None


def test_fallback_rejects_double_slash_reference(tmp_path):
    repo = tmp_path / "app"
    _require(repo)
    _write(os.path.join(repo, "Dockerfile.app"),
           "FROM docker.io//library/python:3.11-slim\nWORKDIR /app\n")
    _write(os.path.join(repo, "main.py"), _SELF_SERVING_APP)
    assert gen_context.generate(str(repo), str(repo))["fallback_dockerfile"] is None


def test_fallback_workdir_none_when_no_workdir_declared(tmp_path):
    repo = tmp_path / "app"
    _require(repo)
    # fallback COPYs the app into /app but declares no WORKDIR: the implicit
    # "/" assumption would start the service from the wrong directory, so
    # the recorded fallback workdir must be None (entry-location probe
    # locates /app/main.py instead)
    _write(os.path.join(repo, "Dockerfile.app"),
           "FROM python:3.11-slim\nCOPY . /app\n"
           "CMD [\"python\", \"/app/main.py\"]\n")
    _write(os.path.join(repo, "main.py"), _SELF_SERVING_APP)
    result = gen_context.generate(str(repo), str(repo))
    assert result["fallback_dockerfile"] == "Dockerfile.app"
    assert result["fallback_workdir"] is None
